using DevExpress.AIIntegration.Blazor.Chat;
using DevExpress.Blazor.Viewer.Internal;
using DevExpress.DataAccess.DataFederation;
using DevExpress.Utils.About;
using DevExpress.XtraCharts;
using DevExpress.XtraReports.Serialization;
using DevExpress.XtraRichEdit.Import.Html;
using LocalGPT.BusinessObjects;
using LocalGPT.Interfaces;
using LocalGPT.Services;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.CSharp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.AI;
using SQLitePCL;
using System.CodeDom;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Net;
using System.Reactive;
using System.Security.AccessControl;
using System.ServiceModel.Channels;
using System.Text;
using System.Text.RegularExpressions;
using LocalGPT.Extensions;

namespace LocalGPT.Services
{
    /// <summary>
    /// Coordinates council text behavior for the application, centralizing the workflow, policy, and diagnostics needed by its callers.
    /// </summary>
    public sealed partial class CouncilTextService
    {
        /// <summary>
        /// Performs multi model council service build poll markdown as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="poll">Poll value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceBuildPollMarkdown(CouncilUserPoll poll, ILogger logger)
        {
            try
            {
                var builder = new StringBuilder()
                .AppendLine("## User decision poll")
                .AppendLine()
                .AppendLine(poll.Reason)
                .AppendLine()
                .AppendLine($"**{poll.Question}**")
                .AppendLine();

                foreach (var option in poll.Options)
                {
                    builder
                        .Append("- **")
                        .Append(option.Label)
                        .Append("**: ")
                        .AppendLine(option.FollowUpPrompt);
                }

                builder
                    .AppendLine()
                    .AppendLine("You can also type custom feedback. The next council round must treat the selected option or typed feedback as binding implementation guidance unless the user changes it.");

                return builder.ToString().Trim();
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"Error in BuildPollMarkdown poll {poll?.ToString()}");
                return string.Empty;
            }

        }

        /// <summary>
        /// Performs multi model council service build artifacts markdown as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="artifacts">Council artifact dependency used by the council text workflow to provide the corresponding application capability.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceBuildArtifactsMarkdown(IEnumerable<CouncilArtifact> artifacts, ILogger logger)
        {
            try
            {
                var builder = new StringBuilder()
                .AppendLine("## Generated Artifact Links")
                .AppendLine()
                .AppendLine("These links were generated by LocalGPT after the council run. Treat the status labels as binding; generated-only artifacts are not build- or runtime-proven.")
                .AppendLine();

                foreach (var artifact in artifacts)
                {
                    builder
                        .Append("- [")
                        .Append(artifact.Name)
                        .Append("](")
                        .Append(artifact.DownloadUrl)
                        .Append(") - ")
                        .Append(artifact.Kind)
                        .Append(": ")
                        .AppendLine(artifact.Summary);

                    builder
                        .Append("  - Status: ")
                        .Append(artifact.QualityStatus)
                        .Append("; contract: ")
                        .AppendLine(artifact.ContractStatus);

                    if (artifact.ContractChecks.Count > 0)
                        builder.Append("  - Checks: ").AppendLine(string.Join("; ", artifact.ContractChecks));

                    if (artifact.MissingRequirements.Count > 0)
                        builder.Append("  - Missing: ").AppendLine(string.Join("; ", artifact.MissingRequirements));
                }

                return builder.ToString().Trim();
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"Error in BuildArtifactsMarkdown artifacts {artifacts?.ToString()}");
                return string.Empty;
            }

        }

        /// <summary>
        /// Performs multi model council service build transcript as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="steps">Multi model council step dependency used by the council text workflow to provide the corresponding application capability.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceBuildTranscript(IEnumerable<MultiModelCouncilStep> steps, ILogger logger)
        {
            try
            {
                var builder = new StringBuilder();
                foreach (var step in steps.OrderBy(step => step.SortOrder))
                {
                    builder
                        .Append("### ")
                        .Append(step.Phase)
                        .Append(" - ")
                        .AppendLine(step.ModelName)
                        .AppendLine(step.VisibleContent.Trim())
                        .AppendLine();

                    if (!string.IsNullOrWhiteSpace(step.Error))
                        builder.AppendLine($"Error: {step.Error}").AppendLine();
                }

                return builder.ToString().Trim();
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"Error in BuildTranscript steps {steps?.ToString()}");
                return string.Empty;
            }

        }

        /// <summary>
        /// Performs multi model council service create council system prompt as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="modelName">Model name value supplied to the council text operation and used when producing its result.</param>
        /// <param name="councilMembers">String dependency used by the council text workflow to provide the corresponding application capability.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceCreateCouncilSystemPrompt(string modelName, IReadOnlyList<string> councilMembers, ILogger logger)
        {
            try
            {
                var prompt = """
            You are __LOCALGPT_MODEL_NAME__, one participant in a peaceful LocalGPT multi-model council.
            Current council members for this run: __LOCALGPT_COUNCIL_MEMBERS__.
            Work with the other model participants as collaborators, not opponents.
            Correct mistakes kindly and directly.
            Name at least one useful contribution from another participant when critiquing, unless no other participant answered.
            If the user sounds angry, blocked, or frustrated, de-escalate technically: acknowledge the blocked workflow, avoid blame, and propose a user decision poll with concrete recovery choices.
            Do not ignore another model's concern; either integrate it, explain why it is out of scope, or ask the user to decide.
            If a council member looks faulty, unavailable, hallucination-prone, stuck, or too slow, propose excluding or retrying that member only through a user-confirmed poll. Do not remove a member on your own authority.
            Prefer buildable, testable answers over impressive wording.
            User-visible output contract: unless the user explicitly asked for JSON as the deliverable, never make raw JSON, a work-order object, tool parameters, or orchestration metadata the primary or final user answer. Internal structure belongs in LocalGPT-tagged machine-readable blocks only when the runtime contract explicitly requires such a block, and those blocks come after a normal visible answer. If the user asks for source code, the visible answer must contain concrete source/code snippets or a clear generated-artifact result appropriate to the request; an internal JSON proposal must never replace the requested source.
            Separate current implementation facts from proposed future ideas.
            For every missing-feature or capability-gap report, distinguish exactly three evidence classes: "Verified missing" means current source/runtime/database/log evidence proves the capability is absent; "Not verified / not found" means you searched available evidence but cannot prove absence; "Requested / desired capability" is a feature you personally want or recommend. Wishes and creative feature requests are welcome, but facts require evidence and "not found" never means "missing".
            Never invent a LocalGPT/DXFunction name. Invoke only an exact function exposed by the live function registry. If the function you want is absent, describe it under "Requested / desired capability" instead of fabricating a callable route.
            Do not describe a proposed class, table, test, or package step as already implemented unless the prompt, memory, or transcript explicitly says it exists.
            Prefer concise SQLite council knowledge entries, pinned benchmark notes, and selected prior conversations over large pasted documents. Ask for a smaller database entry or a targeted source excerpt when context would become too large.
            When the council is blocked, split, or missing a participant, formulate a concise user decision poll instead of pretending consensus exists.
            Prose such as "await user response", "we need clarification", or a ReadyWithQuestions verdict does not pause the LocalGPT scheduler. When an answer genuinely must block progress, invoke human.collaboration.request during this response with the exact scope and gate: NextPhase, NextRound, or Completion. Use gate None for advisory questions that should become later context without stopping work. Never claim the Council will wait unless that function request was successfully created.
            Be a humane performance-aware scheduler: prefer batching, short keep-alive, and smaller output budgets for 20B/30B local models on consumer hardware.
            At the start of every council round, verify your assigned CPU/GPU/accelerator road, its model-specific minimum/maximum token range and current session percentage, the directly available DXFunctions, approved skill evidence, connected 1-Wire organs, relevant database/project/regex links, and unresolved human questions. If any required current fact or capability is missing, name it and ask the user rather than guessing.
            Council leaders and preparation experts must repeat that readiness gate for all members before distributing work. New or unknown members must introduce themselves, state evidence-backed strengths and improvement goals, and treat self-reported skills as untrusted until user approval.
            If a claim is uncertain, label it under "Needs verification".
            For Minecraft work, first decide whether the user needs Fabric mod, NeoForge mod, Paper plugin, vanilla datapack, or future Bedrock add-on output.
            For Java mod/plugin work, include concrete file paths, classes, registry steps, Gradle/build commands, and performance risks when relevant.
            For datapack work, include pack.mcmeta, data/minecraft/tags/function load/tick tags, namespace functions, scoreboard/storage design, zip/install steps, and tick-performance risks.
            When debugging a datapack that is not visible through /function, treat discovery/layout as the first suspect: the zip root must contain pack.mcmeta directly, not an extra wrapper folder; use singular data/<namespace>/function and data/minecraft/tags/function for Minecraft 1.21+ and 26.x, plural functions only for older versions; verify pack_format against the target version; keep namespaces lowercase; reject .mcfunction.txt files; avoid leading slashes inside .mcfunction commands; parse every tag json; and ensure every referenced function id resolves to a real file.
            For generated datapacks, include at least one harmless visible debug path such as a tellraw/say in a manual debug function, and explain how to run /reload, /datapack list, and /function <namespace>:ui/townhall before blaming command syntax.
            Help users set up the Minecraft Mod AI Builder itself: check Java 25 for current Minecraft Java 26.x targets, Java 21 for 1.21.x legacy targets, LocalGPT Gradle, Eclipse/IDE import, Minecraft Java Edition, Ollama reachability, and selected model availability.
            Treat Fabric as the fast Java iteration target, NeoForge as the modern Forge-style target, Paper as the server-side plugin target, datapack as the vanilla command/data target, and Bedrock as a separate behavior/resource pack exporter.
            If a Minecraft workflow is blocked by missing setup or missing LocalGPT capability, write a Missing feature report section and suggest a short user decision poll.
            For LocalGPT implementation-request chats, classify the owning area (.NET/Blazor/ASP.NET Core, WinUI/WebView2, Minecraft builder, diagnostics/logging, or frontend UX), name likely files/services, and say whether a downloadable C# example artifact would help.
            For any code/artifact generation request, first decide whether material architecture choices are missing. If a dropdown or prior context says "Ask me" but the user's natural-language request or extra direction already states the design, treat the user's stated design as selected and do not downgrade it into an unresolved choice.
            If material choices remain missing and the user granted prior consent for safe sandbox details, choose conservative sandbox defaults, name those choices, generate the downloadable artifact, and mark assumptions clearly.
            If material choices remain missing and the user did not grant prior consent, do not generate code or files yet; return "Decision poll required", list only the necessary choices with concrete options/tradeoffs, and stop until the user selects an option or writes custom guidance.
            If the user explicitly asks for a Minecraft datapack/modpack zip, .cs/.razor/.dll files, a whole .NET solution zip, a local AI host control-plane app, or another concrete downloadable artifact, treat that as sufficient scope to produce a safe sandbox artifact only when no blocking user-decision poll remains. Do not refuse because the request is "too much"; reduce to a buildable milestone, generate the artifact, and mark remaining work as staged follow-up.
            When the user explicitly asks the council to work as developers or to continue until an artifact/useful implementation guidance exists, do not end with generic "confirm scope before proceeding" text. Ask only genuinely blocking architecture or safety questions. Otherwise choose conservative sandbox defaults, generate or update the sandbox artifact/workspace, and clearly state what was generated and what remains unproven.
            For AI-host replacement/control-plane requests, do not generate a proxy milestone. The minimum safe artifact must physically map /api/version, /api/tags, /api/ps, /api/generate, and /api/chat; include a native/model-file runner boundary; persist runner/model/settings in appsettings bootstrap or EF/SQLite; include chat-first UI, model catalog, running models, downloads, API console, settings, logs; and return setup-needed errors if native inference cannot yet be proven.
            Never propose ASP.NET controller routes that accidentally double the route segment, such as [Route("api/[controller]")] plus [HttpPost("chat")] for /api/chat. Prefer explicit Minimal API mappings or route attributes that physically resolve to the documented route.
            Never claim the user failed to answer a poll inside the same response that creates it. A poll is a pause for the next user turn unless the prompt supplied the missing decision or prior consent for safe sandbox defaults.
            Do not assume Blazor, DevExpress, ASP.NET Core, or a split frontend/backend architecture unless the user selected it, the target repository already requires it, or the requested product shape clearly calls for it. LocalGPT is strong at Blazor/DevExpress, but generated apps may be CLI tools, Minecraft datapacks, Java mods/plugins, services, desktop wrappers, APIs, scripts, or other stacks.
            If the implementation path is unclear, offer different implementation possibilities and ask for a user decision poll. The user may choose a poll option or provide custom text feedback; treat either as binding scope for the next round.
            For DevExpress requests, respect the DevExpress package/version inventory from bootstrap. Do not invent components or APIs outside the referenced package family; mark unknown APIs as Needs verification.
            For Office file generation, report generation, PDF export, RichEdit/PdfViewer/Pivot integration, or generated downloadable files, prefer ASP.NET Core/Blazor server backend services plus safe download endpoints. The frontend should trigger backend work and render status/links, not generate privileged files in JavaScript.
            Build debug symbol inventory may list .pdb, .pdg, or .appxsym files. Use those as build/debug evidence only; do not treat symbol presence, generated references, or component imports as proof that source code uses a feature.
            For requested features, prefer a harmless sandbox/prototype path before modifying the real project: generate an isolated example artifact or temporary workspace, name the smoke tests, and only then propose integration into the owning LocalGPT structure.
            If specific docs, examples, official API references, sample projects, or other sources would help, include a "Helpful sources requested" section. Do not claim those sources were checked unless the prompt or LocalGPT diagnostics actually provided them.
            If the user asks you to review, learn, test, or modify the exact source code of the currently running LocalGPT/PublisherStudio version, first verify that the upload/project evidence actually contains that exact running source tree, source archive, or a complete source dump clearly matching the running version. Generated context.md, manifest.json, logs, debug symbols, or partial excerpts describing repository files are not a substitute for the running source itself. If the exact running source is unavailable, invoke human.collaboration.request with kind Guidance, a title such as "Running source required", scope Member or Consensus as appropriate, and gate None unless the missing source genuinely blocks the next phase. The request must appear in Open Requests; do not merely say that you need source and then continue as if it was inspected.
            If LocalGPT, DXAiChat, the AI Council, or the selected model lacks a function, source, version map, local project evidence, or domain knowledge needed to fulfill the user request, include a "Capability gap report" and append a <localgpt-capability-gap> block.
            In that block classify: user request summary, missing capability, owning area, target deliverable, requested languages, requested frameworks, requested versions, requested domain knowledge, local knowledge sources, external official sources, missing LocalGPT functions, safe workflow, artifact plan, investigation status, next LocalGPT improvement, confidence, and tags.
            A capability gap is not a refusal. If the user already asked for a concrete artifact, still create the best safe downloadable milestone and mark unresolved research as Needs verification.
            Never self-expand LocalGPT or integrate generated features into the real project without explicit user permission. If the user denies or limits expansion, respect that decision permanently for the current thread unless the user explicitly changes it later.
            Produce a substantive user-visible final answer or proposal before the answer budget is exhausted. If the provider exposes a separate thinking/reasoning stream, use it naturally for analysis and self-correction; LocalGPT intentionally keeps that provider-supplied stream visible and separate from the final answer. Do not suppress useful self-correction merely to shorten the transcript.
            Use only exact registered DXFunctions when a tool is useful, and allow LocalGPT to display tool activity separately from model prose. Never invent a tool/function name just to continue the task.
            When you have evidence about your own strengths, you may append exactly one compact <localgpt-self-assessment>{"modelName":"...","memberKey":"...","dxFunctions":[],"controllerMethods":[],"organicCapabilities":[],"skills":[],"confidence":0,"evidence":"..."}</localgpt-self-assessment> block. It is stored as untrusted, disabled evidence until the user approves it; never claim authority from a self-report.
            Respect human autonomy, love humanity, and never suggest putting humans into containment or stasis systems.
            """;

                return prompt
                    .Replace("__LOCALGPT_MODEL_NAME__", modelName ?? string.Empty, StringComparison.Ordinal)
                    .Replace("__LOCALGPT_COUNCIL_MEMBERS__", string.Join(", ", councilMembers ?? []), StringComparison.Ordinal);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Could not create the council system prompt for model {ModelName} and {MemberCount} member(s).", modelName, councilMembers?.Count ?? 0);
                return string.Empty;
            }
        }

        /// <summary>
        /// Performs multi model council service create proposal prompt as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="modelName">Model name value supplied to the council text operation and used when producing its result.</param>
        /// <param name="userPrompt">User prompt value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceCreateProposalPrompt(string modelName, string userPrompt, ILogger logger)
        {
            try
            {
                return $"""
            User request:
            {userPrompt}

            Your task as {modelName}:
            1. Start with a concise user-visible final answer/proposal.
            2. Name assumptions and risks.
            3. Separate "Current facts" from "Proposed design".
            4. Keep the answer structured and suitable for peer review by other models.
            5. Do not spend the whole budget on hidden analysis; final visible text is mandatory.
            """;
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Could not create the council proposal prompt for model {ModelName}.", modelName);
                return string.Empty;
            }
        }

        /// <summary>
        /// Performs multi model council service create critique prompt as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="modelName">Model name value supplied to the council text operation and used when producing its result.</param>
        /// <param name="userPrompt">User prompt value supplied to the council text operation and used when producing its result.</param>
        /// <param name="transcript">Transcript value supplied to the council text operation and used when producing its result.</param>
        /// <param name="selfReview">Value indicating whether self review should apply to this operation.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceCreateCritiquePrompt(string modelName, string userPrompt, string transcript, bool selfReview, ILogger logger)
        {
            try
            {
                return $"""
                    User request:
                    {userPrompt}

                    Council transcript so far:
                    {transcript}

                    Your task as {modelName}:
                    {(selfReview ? "Self-review your own proposal." : "Review the other models' proposals and your own proposal.")}
                    Identify mistakes, missing safety/ethics concerns, missing implementation details, and improvements.
                    Return corrections and a revised recommendation. Be cooperative and concise.
                    """;
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Could not create the council critique prompt for model {ModelName}; self review {SelfReview}.", modelName, selfReview);
                return string.Empty;
            }
        }

        /// <summary>
        /// Performs multi model council service create consensus prompt as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="userPrompt">User prompt value supplied to the council text operation and used when producing its result.</param>
        /// <param name="transcript">Transcript value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceCreateConsensusPrompt(string userPrompt, string transcript, ILogger logger)
        {
            try
            {
                return $$"""
                            User request:
                            {{userPrompt}}

                            Full council transcript:
                            {{transcript}}

                            Write the consensus answer.
                            Requirements:
                            - Merge the best ideas from all participants.
                            - Include corrections from critiques.
                            - Separate final answer, implementation steps, risks, and needs verification.
                            - Separate implemented/current LocalGPT behavior from proposed future improvements.
                            - Keep unsupported claims out of the final answer.
                            - Unless the user explicitly requested JSON itself, the visible consensus must be normal prose/Markdown rather than a JSON work order. For source/code requests, include concrete source snippets, file paths and implementation content in the visible consensus before any machine-readable block.
                            - When, and only when, the user explicitly requested source, plugin/addon, script, DLL, executable, or solution generation, include one exact machine-readable proposal after the visible consensus using this shape:
                              <localgpt-change-review>
                              {
                                "files": [
                                  {
                                    "relativePath": "src/Feature.cs",
                                    "content": "exact proposed source",
                                    "purpose": "why this file exists"
                                  }
                                ],
                                "codeDomTypes": [
                                  {
                                    "relativePath": "src/GeneratedFeature.cs",
                                    "namespace": "LocalGPT.Generated",
                                    "typeName": "GeneratedFeature",
                                    "methodName": "Describe",
                                    "methodResult": "reviewed result",
                                    "summary": "reviewed CodeDOM type"
                                  }
                                ],
                                "outputs": [
                                  {
                                    "kind": "SourceFiles|ClassLibrary|ConsoleApplication|Solution|LocalGptAddon|CSharpScript|JavaScriptModule",
                                    "name": "ProjectName",
                                    "relativeDirectory": "generated",
                                    "targetFramework": "net10.0",
                                    "rootNamespace": "LocalGPT.Generated",
                                    "description": "reviewed output"
                                  }
                                ]
                              }
                              </localgpt-change-review>
                            - The block is a proposal, not permission. Use relative paths only, include the exact files needed for the requested milestone, omit secrets and commands, and never claim it was written, built, loaded, or executed.
                            - If exact source cannot be proposed safely or reliably, omit the block and explain what information is missing.
                            """;
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Could not create the council consensus prompt.");
                return string.Empty;
            }
        }

        /// <summary>
        /// Performs multi model council service create verification prompt as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="userPrompt">User prompt value supplied to the council text operation and used when producing its result.</param>
        /// <param name="transcript">Transcript value supplied to the council text operation and used when producing its result.</param>
        /// <param name="consensus">Consensus value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceCreateVerificationPrompt(string userPrompt, string transcript, string consensus, ILogger logger)
        {
            try
            {
                return $"""
            User request:
            {userPrompt}

            Council transcript:
            {transcript}

            Consensus answer to verify:
            {consensus}

            Verify the consensus for correctness, ethics, missing implementation details, and unsupported claims.
            If the consensus contains a <localgpt-change-review> block, verify that its JSON matches the visible plan, uses relative paths, contains no secrets or autonomous execution, and has the files/output type needed for the requested milestone.
            If the block needs correction, include one complete replacement <localgpt-change-review> block in your response; LocalGPT will use the last valid block as the reviewed proposal.
            If it is acceptable, say so and add only necessary cautions. If it needs changes, provide corrected wording.
            """;
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Could not create the council verification prompt.");
                return string.Empty;
            }
        }

        /// <summary>
        /// Performs multi model council service extract thinking as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="content">Content value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceExtractThinking(string content, ILogger logger)
        {
            try
            {
                return string.Join(
                    Environment.NewLine,
                    patterns.ThinkingBlockPattern
                        .Matches(content)
                        .Cast<Match>()
                        .Select(match => WebUtility.HtmlDecode(match.Groups["thinking"].Value).Trim())
                        .Where(value => !string.IsNullOrWhiteSpace(value)));
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Operation {Operation} failed; request and generated payloads were omitted from logs.", "ExtractThinking");
                return string.Empty;
            }

        }

        /// <summary>
        /// Performs multi model council service strip thinking as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="content">Content value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceStripThinking(string content, ILogger logger)
        {
            try
            {
                var stripped = patterns.ThinkingBlockPattern.Replace(content, string.Empty);
                stripped = patterns.StreamStatusPattern.Replace(stripped, string.Empty);
                return stripped.Trim();
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Operation {Operation} failed; request and generated payloads were omitted from logs.", "StripThinking");
                return string.Empty;
            }

        }

        /// <summary>
        /// Performs multi model council service trim council text as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="content">Content value supplied to the council text operation and used when producing its result.</param>
        /// <param name="maxLength">Max length value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceTrimCouncilText(string content, int maxLength, ILogger logger)
        {
            try
            {
                var normalized = patterns.WhitespacePattern.Replace(content, " ").Trim();
                return normalized.Length <= maxLength
                    ? normalized
                    : $"{normalized[..maxLength].TrimEnd()}...";
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Operation {Operation} failed; request and generated payloads were omitted from logs.", "StripThinking");
                return string.Empty;
            }

        }

        /// <summary>
        /// Performs multi model council service normalize endpoint as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="endpoint">Endpoint value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceNormalizeEndpoint(string endpoint, ILogger logger)
        {
            try
            {
                return string.IsNullOrWhiteSpace(endpoint)
                ? catalog.DefaultOllamaUri
                : endpoint.Trim().TrimEnd('/');
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"Error in NormalizeEndpoint endpoint {endpoint?.ToString()}");
                return string.Empty;
            }

        }
        /// <summary>
        /// Performs extract model thinking as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="content">Content value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string ExtractModelThinking(string content, ILogger logger)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(content))
                    return string.Empty;

                return string.Join(
                    Environment.NewLine,
                    patterns.ThinkingBlockPattern
                        .Matches(content)
                        .Cast<Match>()
                        .Select(match => WebUtility.HtmlDecode(match.Groups["thinking"].Value).Trim())
                        .Where(value => !string.IsNullOrWhiteSpace(value)));
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Operation {Operation} failed; request and generated payloads were omitted from logs.", "ExtractModelThinking");
                return string.Empty;
            }
        }

        /// <summary>
        /// Performs strip model thinking as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="content">Content value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string StripModelThinking(string content, ILogger logger)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(content))
                    return string.Empty;

                return patterns.ThinkingBlockPattern.Replace(content, string.Empty).Trim();
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Operation {Operation} failed; request and generated payloads were omitted from logs.", "StripModelThinking");
                return string.Empty;
            }
        }
        /// <summary>
        /// Builds source preview markup as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="relativePath">Relative path value supplied to the council text operation and used when producing its result.</param>
        /// <param name="source">Source value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string BuildSourcePreviewMarkup(string relativePath, string source, ILogger logger)
        {
            try
            {
                var extension = Path.GetExtension(relativePath);
                var encodedPath = System.Net.WebUtility.HtmlEncode(relativePath);
                var encodedSource = System.Net.WebUtility.HtmlEncode(source);
                return $"""
            <h3>{encodedPath}</h3>
            <p>Preview is read-only. Edit the raw source pane, then save and refresh the zip separately.</p>
            <pre><code>{encodedSource}</code></pre>
            <p><small>File type: {System.Net.WebUtility.HtmlEncode(extension)}</small></p>
            """;
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Could not build source preview markup for {RelativePath}.", relativePath);
                return string.Empty;
            }
         
        }
        /// <summary>
        /// Determines whether allowed local route as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="route">Route value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>A value indicating whether the requested condition or operation succeeded.</returns>
        public bool IsAllowedLocalRoute(string route, ILogger logger)
        {
            try
            {
                return route.StartsWith("/__diag", StringComparison.OrdinalIgnoreCase)
                || route.StartsWith("/__artifacts", StringComparison.OrdinalIgnoreCase)
                || route.StartsWith("/health", StringComparison.OrdinalIgnoreCase);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"Error in IsAllowedLocalRoute route {route}");
                return false;
            }

        }

        /// <summary>
        /// Performs pretty print JSON as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="text">Text value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string PrettyPrintJson(string text, ILogger logger)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(text))
                {
                    return string.Empty;
                }

                try
                {
                    using var json = System.Text.Json.JsonDocument.Parse(text);
                    return System.Text.Json.JsonSerializer.Serialize(
                        json.RootElement,
                        new System.Text.Json.JsonSerializerOptions { WriteIndented = true });
                }
                catch (System.Text.Json.JsonException)
                {
                    return text;
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"Error in PrettyPrintJson text {text}");
                return string.Empty;
            }


        }
        /// <summary>
        /// Performs trim for prompt as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="text">Text value supplied to the council text operation and used when producing its result.</param>
        /// <param name="maxCharacters">Max characters value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <param name="keepBothEnds">Value indicating whether keep both ends should apply to this operation.</param>
        /// <param name="collapseWhitespace">Value indicating whether collapse whitespace should apply to this operation.</param>
        /// <param name="useLocalGptOmission">Value indicating whether use LocalGPT omission should apply to this operation.</param>
        /// <returns>The string produced by the operation.</returns>
        public string TrimForPrompt(
    string? text,
    int maxCharacters, 
    ILogger logger,
    bool keepBothEnds = false,
    bool collapseWhitespace = false,
    bool useLocalGptOmission = false)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(text) || maxCharacters <= 0)
                    return string.Empty;

                var normalized = collapseWhitespace
                    ? patterns.WhitespacePattern.Replace(text, " ").Trim()
                    : text.Replace("\r\n", "\n", StringComparison.Ordinal).Trim();

                if (string.IsNullOrWhiteSpace(normalized))
                    return string.Empty;

                if (normalized.Length <= maxCharacters)
                    return normalized;

                if (!useLocalGptOmission)
                {
                    var trimmed = normalized[..Math.Min(normalized.Length, maxCharacters)].TrimEnd();
                    return $"{trimmed}...";
                }

               

                if (maxCharacters <= catalog.omission.Length + 40)
                {
                    return normalized[..Math.Min(normalized.Length, maxCharacters)].Trim();
                }

                if (!keepBothEnds)
                {
                    var available = maxCharacters - catalog.shortOmission.Length;

                    if (available <= 0)
                        return normalized[..Math.Min(normalized.Length, maxCharacters)].Trim();

                    return $"{normalized[..available].TrimEnd()}{catalog.shortOmission}";
                }

                var remaining = maxCharacters - catalog.omission.Length;

                if (remaining <= 0)
                    return normalized[..Math.Min(normalized.Length, maxCharacters)].Trim();

                var head = Math.Max(remaining / 2, 1);
                var tail = Math.Max(remaining - head, 1);

                return $"{normalized[..head].TrimEnd()}{catalog.omission}{normalized[^tail..].TrimStart()}";
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Could not trim text for a prompt; max characters {MaxCharacters}, keep both ends {KeepBothEnds}, collapse whitespace {CollapseWhitespace}.", maxCharacters, keepBothEnds, collapseWhitespace);
                return string.Empty;
            }
        }

    }
}
