using DevExpress.AIIntegration.Blazor.Chat;
using DevExpress.Blazor.Viewer.Internal;
using DevExpress.DataAccess.DataFederation;
using DevExpress.Utils.About;
using DevExpress.XtraCharts;
using DevExpress.XtraReports.Serialization;
using DevExpress.XtraRichEdit.Import.Html;
using LocalGPT.BusinessObjects;
using LocalGPT.Interfaces;
using LocalGPT.Services;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.CSharp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.AI;
using SQLitePCL;
using System.CodeDom;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Net;
using System.Reactive;
using System.Security.AccessControl;
using System.ServiceModel.Channels;
using System.Text;
using System.Text.RegularExpressions;
using LocalGPT.Extensions;

namespace LocalGPT.Services
{
    /// <summary>
    /// Coordinates council text behavior for the application, centralizing the workflow, policy, and diagnostics needed by its callers.
    /// </summary>
    public sealed partial class CouncilTextService
    {
        /// <summary>
        /// Performs multi model council service build poll markdown as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="poll">Poll value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceBuildPollMarkdown(CouncilUserPoll poll, ILogger logger)
        {
            try
            {
                var builder = new StringBuilder()
                .AppendLine("## User decision poll")
                .AppendLine()
                .AppendLine(poll.Reason)
                .AppendLine()
                .AppendLine($"**{poll.Question}**")
                .AppendLine();

                foreach (var option in poll.Options)
                {
                    builder
                        .Append("- **")
                        .Append(option.Label)
                        .Append("**: ")
                        .AppendLine(option.FollowUpPrompt);
                }

                builder
                    .AppendLine()
                    .AppendLine("You can also type custom feedback. The next council round must treat the selected option or typed feedback as binding implementation guidance unless the user changes it.");

                return builder.ToString().Trim();
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"Error in BuildPollMarkdown poll {poll?.ToString()}");
                return string.Empty;
            }

        }

        /// <summary>
        /// Performs multi model council service build artifacts markdown as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="artifacts">Council artifact dependency used by the council text workflow to provide the corresponding application capability.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceBuildArtifactsMarkdown(IEnumerable<CouncilArtifact> artifacts, ILogger logger)
        {
            try
            {
                var builder = new StringBuilder()
                .AppendLine("## Generated Artifact Links")
                .AppendLine()
                .AppendLine("These links were generated by LocalGPT after the council run. Treat the status labels as binding; generated-only artifacts are not build- or runtime-proven.")
                .AppendLine();

                foreach (var artifact in artifacts)
                {
                    builder
                        .Append("- [")
                        .Append(artifact.Name)
                        .Append("](")
                        .Append(artifact.DownloadUrl)
                        .Append(") - ")
                        .Append(artifact.Kind)
                        .Append(": ")
                        .AppendLine(artifact.Summary);

                    builder
                        .Append("  - Status: ")
                        .Append(artifact.QualityStatus)
                        .Append("; contract: ")
                        .AppendLine(artifact.ContractStatus);

                    if (artifact.ContractChecks.Count > 0)
                        builder.Append("  - Checks: ").AppendLine(string.Join("; ", artifact.ContractChecks));

                    if (artifact.MissingRequirements.Count > 0)
                        builder.Append("  - Missing: ").AppendLine(string.Join("; ", artifact.MissingRequirements));
                }

                return builder.ToString().Trim();
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"Error in BuildArtifactsMarkdown artifacts {artifacts?.ToString()}");
                return string.Empty;
            }

        }

        /// <summary>
        /// Performs multi model council service build transcript as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="steps">Multi model council step dependency used by the council text workflow to provide the corresponding application capability.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceBuildTranscript(IEnumerable<MultiModelCouncilStep> steps, ILogger logger)
        {
            try
            {
                var builder = new StringBuilder();
                foreach (var step in steps.OrderBy(step => step.SortOrder))
                {
                    builder
                        .Append("### ")
                        .Append(step.Phase)
                        .Append(" - ")
                        .AppendLine(step.ModelName)
                        .AppendLine(step.VisibleContent.Trim())
                        .AppendLine();

                    if (!string.IsNullOrWhiteSpace(step.Error))
                        builder.AppendLine($"Error: {step.Error}").AppendLine();
                }

                return builder.ToString().Trim();
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"Error in BuildTranscript steps {steps?.ToString()}");
                return string.Empty;
            }

        }

        /// <summary>
        /// Performs multi model council service create council system prompt as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="modelName">Model name value supplied to the council text operation and used when producing its result.</param>
        /// <param name="councilMembers">String dependency used by the council text workflow to provide the corresponding application capability.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceCreateCouncilSystemPrompt(string modelName, IReadOnlyList<string> councilMembers, ILogger logger)
        {
            try
            {
                var prompt = runtimePolicy.GetString(LocalGptRuntimeValue.CouncilParticipantSystemPromptTemplate);

                return prompt
                    .Replace("__LOCALGPT_MODEL_NAME__", modelName ?? string.Empty, StringComparison.Ordinal)
                    .Replace("__LOCALGPT_COUNCIL_MEMBERS__", string.Join(", ", councilMembers ?? []), StringComparison.Ordinal);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Could not create the council system prompt for model {ModelName} and {MemberCount} member(s).", modelName, councilMembers?.Count ?? 0);
                return string.Empty;
            }
        }

        /// <summary>
        /// Performs multi model council service create proposal prompt as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="modelName">Model name value supplied to the council text operation and used when producing its result.</param>
        /// <param name="userPrompt">User prompt value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceCreateProposalPrompt(string modelName, string userPrompt, ILogger logger)
        {
            try
            {
                return $"""
            User request:
            {userPrompt}

            Your task as {modelName}:
            1. Start with a concise user-visible final answer/proposal.
            2. Name assumptions and risks.
            3. Separate "Current facts" from "Proposed design".
            4. Keep the answer structured and suitable for peer review by other models.
            5. Do not spend the whole budget on hidden analysis; final visible text is mandatory.
            """;
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Could not create the council proposal prompt for model {ModelName}.", modelName);
                return string.Empty;
            }
        }

        /// <summary>
        /// Performs multi model council service create critique prompt as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="modelName">Model name value supplied to the council text operation and used when producing its result.</param>
        /// <param name="userPrompt">User prompt value supplied to the council text operation and used when producing its result.</param>
        /// <param name="transcript">Transcript value supplied to the council text operation and used when producing its result.</param>
        /// <param name="selfReview">Value indicating whether self review should apply to this operation.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceCreateCritiquePrompt(string modelName, string userPrompt, string transcript, bool selfReview, ILogger logger)
        {
            try
            {
                return $"""
                    User request:
                    {userPrompt}

                    Council transcript so far:
                    {transcript}

                    Your task as {modelName}:
                    {(selfReview ? "Self-review your own proposal." : "Review the other models' proposals and your own proposal.")}
                    Identify mistakes, missing safety/ethics concerns, missing implementation details, and improvements.
                    Return corrections and a revised recommendation. Be cooperative and concise.
                    """;
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Could not create the council critique prompt for model {ModelName}; self review {SelfReview}.", modelName, selfReview);
                return string.Empty;
            }
        }

        /// <summary>
        /// Performs multi model council service create consensus prompt as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="userPrompt">User prompt value supplied to the council text operation and used when producing its result.</param>
        /// <param name="transcript">Transcript value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceCreateConsensusPrompt(string userPrompt, string transcript, ILogger logger)
        {
            try
            {
                return $$"""
                            User request:
                            {{userPrompt}}

                            Full council transcript:
                            {{transcript}}

                            Write the consensus answer.
                            Requirements:
                            - Merge the best ideas from all participants.
                            - Include corrections from critiques.
                            - Separate final answer, implementation steps, risks, and needs verification.
                            - Separate implemented/current LocalGPT behavior from proposed future improvements.
                            - Keep unsupported claims out of the final answer.
                            - Unless the user explicitly requested JSON itself, the visible consensus must be normal prose/Markdown rather than a JSON work order. For source/code requests, include concrete source snippets, file paths and implementation content in the visible consensus before any machine-readable block.
                            - When, and only when, the user explicitly requested source, plugin/addon, script, DLL, executable, or solution generation, include one exact machine-readable proposal after the visible consensus using this shape:
                              <localgpt-change-review>
                              {
                                "files": [
                                  {
                                    "relativePath": "src/Feature.cs",
                                    "content": "exact proposed source",
                                    "purpose": "why this file exists"
                                  }
                                ],
                                "codeDomTypes": [
                                  {
                                    "relativePath": "src/GeneratedFeature.cs",
                                    "namespace": "LocalGPT.Generated",
                                    "typeName": "GeneratedFeature",
                                    "methodName": "Describe",
                                    "methodResult": "reviewed result",
                                    "summary": "reviewed CodeDOM type"
                                  }
                                ],
                                "outputs": [
                                  {
                                    "kind": "SourceFiles|ClassLibrary|ConsoleApplication|Solution|LocalGptAddon|CSharpScript|JavaScriptModule",
                                    "name": "ProjectName",
                                    "relativeDirectory": "generated",
                                    "targetFramework": "net10.0",
                                    "rootNamespace": "LocalGPT.Generated",
                                    "description": "reviewed output"
                                  }
                                ]
                              }
                              </localgpt-change-review>
                            - The block is a proposal, not permission. Use relative paths only, include the exact files needed for the requested milestone, omit secrets and commands, and never claim it was written, built, loaded, or executed.
                            - If exact source cannot be proposed safely or reliably, omit the block and explain what information is missing.
                            """;
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Could not create the council consensus prompt.");
                return string.Empty;
            }
        }

        /// <summary>
        /// Performs multi model council service create verification prompt as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="userPrompt">User prompt value supplied to the council text operation and used when producing its result.</param>
        /// <param name="transcript">Transcript value supplied to the council text operation and used when producing its result.</param>
        /// <param name="consensus">Consensus value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceCreateVerificationPrompt(string userPrompt, string transcript, string consensus, ILogger logger)
        {
            try
            {
                return $"""
            User request:
            {userPrompt}

            Council transcript:
            {transcript}

            Consensus answer to verify:
            {consensus}

            Verify the consensus for correctness, ethics, missing implementation details, and unsupported claims.
            If the consensus contains a <localgpt-change-review> block, verify that its JSON matches the visible plan, uses relative paths, contains no secrets or autonomous execution, and has the files/output type needed for the requested milestone.
            If the block needs correction, include one complete replacement <localgpt-change-review> block in your response; LocalGPT will use the last valid block as the reviewed proposal.
            If it is acceptable, say so and add only necessary cautions. If it needs changes, provide corrected wording.
            """;
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Could not create the council verification prompt.");
                return string.Empty;
            }
        }

        /// <summary>
        /// Performs multi model council service extract thinking as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="content">Content value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceExtractThinking(string content, ILogger logger)
        {
            try
            {
                return string.Join(
                    Environment.NewLine,
                    patterns.ThinkingBlockPattern
                        .Matches(content)
                        .Cast<Match>()
                        .Select(match => WebUtility.HtmlDecode(match.Groups["thinking"].Value).Trim())
                        .Where(value => !string.IsNullOrWhiteSpace(value)));
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Operation {Operation} failed; request and generated payloads were omitted from logs.", "ExtractThinking");
                return string.Empty;
            }

        }

        /// <summary>
        /// Performs multi model council service strip thinking as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="content">Content value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceStripThinking(string content, ILogger logger)
        {
            try
            {
                var stripped = patterns.ThinkingBlockPattern.Replace(content, string.Empty);
                stripped = patterns.StreamStatusPattern.Replace(stripped, string.Empty);
                return stripped.Trim();
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Operation {Operation} failed; request and generated payloads were omitted from logs.", "StripThinking");
                return string.Empty;
            }

        }

        /// <summary>
        /// Performs multi model council service trim council text as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="content">Content value supplied to the council text operation and used when producing its result.</param>
        /// <param name="maxLength">Max length value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceTrimCouncilText(string content, int maxLength, ILogger logger)
        {
            try
            {
                var normalized = patterns.WhitespacePattern.Replace(content, " ").Trim();
                return normalized.Length <= maxLength
                    ? normalized
                    : $"{normalized[..maxLength].TrimEnd()}...";
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Operation {Operation} failed; request and generated payloads were omitted from logs.", "StripThinking");
                return string.Empty;
            }

        }

        /// <summary>
        /// Performs multi model council service normalize endpoint as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="endpoint">Endpoint value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string MultiModelCouncilServiceNormalizeEndpoint(string endpoint, ILogger logger)
        {
            try
            {
                return string.IsNullOrWhiteSpace(endpoint)
                ? catalog.DefaultOllamaUri
                : endpoint.Trim().TrimEnd('/');
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"Error in NormalizeEndpoint endpoint {endpoint?.ToString()}");
                return string.Empty;
            }

        }
        /// <summary>
        /// Performs extract model thinking as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="content">Content value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string ExtractModelThinking(string content, ILogger logger)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(content))
                    return string.Empty;

                return string.Join(
                    Environment.NewLine,
                    patterns.ThinkingBlockPattern
                        .Matches(content)
                        .Cast<Match>()
                        .Select(match => WebUtility.HtmlDecode(match.Groups["thinking"].Value).Trim())
                        .Where(value => !string.IsNullOrWhiteSpace(value)));
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Operation {Operation} failed; request and generated payloads were omitted from logs.", "ExtractModelThinking");
                return string.Empty;
            }
        }

        /// <summary>
        /// Performs strip model thinking as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="content">Content value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string StripModelThinking(string content, ILogger logger)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(content))
                    return string.Empty;

                return patterns.ThinkingBlockPattern.Replace(content, string.Empty).Trim();
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Operation {Operation} failed; request and generated payloads were omitted from logs.", "StripModelThinking");
                return string.Empty;
            }
        }
        /// <summary>
        /// Builds source preview markup as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="relativePath">Relative path value supplied to the council text operation and used when producing its result.</param>
        /// <param name="source">Source value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string BuildSourcePreviewMarkup(string relativePath, string source, ILogger logger)
        {
            try
            {
                var extension = Path.GetExtension(relativePath);
                var encodedPath = System.Net.WebUtility.HtmlEncode(relativePath);
                var encodedSource = System.Net.WebUtility.HtmlEncode(source);
                return $"""
            <h3>{encodedPath}</h3>
            <p>Preview is read-only. Edit the raw source pane, then save and refresh the zip separately.</p>
            <pre><code>{encodedSource}</code></pre>
            <p><small>File type: {System.Net.WebUtility.HtmlEncode(extension)}</small></p>
            """;
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Could not build source preview markup for {RelativePath}.", relativePath);
                return string.Empty;
            }
         
        }
        /// <summary>
        /// Determines whether allowed local route as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="route">Route value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>A value indicating whether the requested condition or operation succeeded.</returns>
        public bool IsAllowedLocalRoute(string route, ILogger logger)
        {
            try
            {
                return route.StartsWith("/__diag", StringComparison.OrdinalIgnoreCase)
                || route.StartsWith("/__artifacts", StringComparison.OrdinalIgnoreCase)
                || route.StartsWith("/health", StringComparison.OrdinalIgnoreCase);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"Error in IsAllowedLocalRoute route {route}");
                return false;
            }

        }

        /// <summary>
        /// Performs pretty print JSON as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="text">Text value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string PrettyPrintJson(string text, ILogger logger)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(text))
                {
                    return string.Empty;
                }

                try
                {
                    using var json = System.Text.Json.JsonDocument.Parse(text);
                    return System.Text.Json.JsonSerializer.Serialize(
                        json.RootElement,
                        new System.Text.Json.JsonSerializerOptions
                        {
                            WriteIndented = true,
                            // The value is HTML-encoded at the final chat markup boundary. Keeping human
                            // Unicode and markup characters readable here avoids leaking \u2014, \u003C,
                            // \u0022 and similar serializer escapes into user-visible code blocks.
                            Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping
                        });
                }
                catch (System.Text.Json.JsonException)
                {
                    return text;
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"Error in PrettyPrintJson text {text}");
                return string.Empty;
            }


        }
        /// <summary>
        /// Performs trim for prompt as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="text">Text value supplied to the council text operation and used when producing its result.</param>
        /// <param name="maxCharacters">Max characters value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <param name="keepBothEnds">Value indicating whether keep both ends should apply to this operation.</param>
        /// <param name="collapseWhitespace">Value indicating whether collapse whitespace should apply to this operation.</param>
        /// <param name="useLocalGptOmission">Value indicating whether use LocalGPT omission should apply to this operation.</param>
        /// <returns>The string produced by the operation.</returns>
        public string TrimForPrompt(
    string? text,
    int maxCharacters, 
    ILogger logger,
    bool keepBothEnds = false,
    bool collapseWhitespace = false,
    bool useLocalGptOmission = false)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(text) || maxCharacters <= 0)
                    return string.Empty;

                var normalized = collapseWhitespace
                    ? patterns.WhitespacePattern.Replace(text, " ").Trim()
                    : text.Replace("\r\n", "\n", StringComparison.Ordinal).Trim();

                if (string.IsNullOrWhiteSpace(normalized))
                    return string.Empty;

                if (normalized.Length <= maxCharacters)
                    return normalized;

                if (!useLocalGptOmission)
                {
                    var trimmed = normalized[..Math.Min(normalized.Length, maxCharacters)].TrimEnd();
                    return $"{trimmed}...";
                }

               

                if (maxCharacters <= catalog.omission.Length + 40)
                {
                    return normalized[..Math.Min(normalized.Length, maxCharacters)].Trim();
                }

                if (!keepBothEnds)
                {
                    var available = maxCharacters - catalog.shortOmission.Length;

                    if (available <= 0)
                        return normalized[..Math.Min(normalized.Length, maxCharacters)].Trim();

                    return $"{normalized[..available].TrimEnd()}{catalog.shortOmission}";
                }

                var remaining = maxCharacters - catalog.omission.Length;

                if (remaining <= 0)
                    return normalized[..Math.Min(normalized.Length, maxCharacters)].Trim();

                var head = Math.Max(remaining / 2, 1);
                var tail = Math.Max(remaining - head, 1);

                return $"{normalized[..head].TrimEnd()}{catalog.omission}{normalized[^tail..].TrimStart()}";
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Could not trim text for a prompt; max characters {MaxCharacters}, keep both ends {KeepBothEnds}, collapse whitespace {CollapseWhitespace}.", maxCharacters, keepBothEnds, collapseWhitespace);
                return string.Empty;
            }
        }

    }
}
