using System.IO.Compression;
using System.Text;
using System.Text.Json;
using LocalGPT.BusinessObjects;
using LocalGPT.Interfaces;

namespace LocalGPT.Services
{
    /// <summary>
    /// Coordinates embedded firmware planning behavior for the application, centralizing the workflow, policy, and diagnostics needed by its callers.
    /// </summary>
    public sealed partial class EmbeddedFirmwarePlanningService
    {
    /// <summary>
    /// Builds arduino sketch as part of the embedded firmware planning service workflow, applying the service's runtime policy, state management, and diagnostics as required.
    /// </summary>
    /// <param name="plan">Plan value supplied to the embedded firmware planning operation and used when producing its result.</param>
    /// <returns>The string produced by the operation.</returns>
    private string BuildArduinoSketch(EmbeddedFirmwarePlan plan)
    {
    try
    {
            var physicalOneWireGroups = plan.PinAssignments
                .Where(item => item.ProtocolKey == EmbeddedProtocolKeys.PhysicalOneWire)
                .GroupBy(item => item.PinKey, StringComparer.OrdinalIgnoreCase)
                .ToList();
            var includes = physicalOneWireGroups.Count > 0 ? "#include <OneWire.h>\n#include <DallasTemperature.h>" : string.Empty;
            var declarations = string.Join(Environment.NewLine, plan.PinAssignments
                .GroupBy(item => item.PinKey, StringComparer.OrdinalIgnoreCase)
                .Select((group, index) => $"constexpr int PIN_{SanitizeIdentifier(group.Key, index)} = {group.First().Gpio};"));
            var oneWireDeclarations = string.Join(Environment.NewLine, physicalOneWireGroups.Select((group, index) =>
                $"OneWire oneWireBus{index}(PIN_{SanitizeIdentifier(group.Key, index)});\nDallasTemperature oneWireSensors{index}(&oneWireBus{index});"));
            var setupPins = string.Join(Environment.NewLine, plan.PinAssignments
                .GroupBy(item => item.PinKey, StringComparer.OrdinalIgnoreCase)
                .Select((group, index) => $"  pinMode(PIN_{SanitizeIdentifier(group.Key, index)}, {ArduinoPinMode(group.First().Mode)});"));
            var oneWireSetup = string.Join(Environment.NewLine, physicalOneWireGroups.Select((_, index) => $"  oneWireSensors{index}.begin();"));
            var emitCalls = new StringBuilder();
            var pinGroups = plan.PinAssignments.GroupBy(item => item.PinKey, StringComparer.OrdinalIgnoreCase).ToList();
            foreach (var assignment in plan.PinAssignments)
            {
                var pinIndex = pinGroups.FindIndex(group => string.Equals(group.Key, assignment.PinKey, StringComparison.OrdinalIgnoreCase));
                var constant = $"PIN_{SanitizeIdentifier(assignment.PinKey, pinIndex)}";
                if (assignment.ProtocolKey == EmbeddedProtocolKeys.PhysicalOneWire)
                {
                    var busIndex = physicalOneWireGroups.FindIndex(group => string.Equals(group.Key, assignment.PinKey, StringComparison.OrdinalIgnoreCase));
                    var sensorIndex = physicalOneWireGroups[busIndex].ToList().FindIndex(item => ReferenceEquals(item, assignment));
                    emitCalls.AppendLine($"  oneWireSensors{busIndex}.requestTemperatures();");
                    emitCalls.AppendLine($"  publishReading(\"{EscapeCpp(assignment.SensorKey)}\", \"{EscapeCpp(assignment.PinKey)}\", {assignment.Gpio}, \"{EscapeCpp(assignment.Metric)}\", oneWireSensors{busIndex}.getTempCByIndex({Math.Max(0, sensorIndex)}), \"{EscapeCpp(assignment.Unit)}\");");
                }
                else if (assignment.ProtocolKey == EmbeddedProtocolKeys.AnalogAdc)
                {
                    emitCalls.AppendLine($"  publishReading(\"{EscapeCpp(assignment.SensorKey)}\", \"{EscapeCpp(assignment.PinKey)}\", {assignment.Gpio}, \"{EscapeCpp(assignment.Metric)}\", analogRead({constant}), \"{EscapeCpp(assignment.Unit)}\");");
                }
                else if (assignment.ProtocolKey == EmbeddedProtocolKeys.DigitalGpio)
                {
                    emitCalls.AppendLine($"  publishReading(\"{EscapeCpp(assignment.SensorKey)}\", \"{EscapeCpp(assignment.PinKey)}\", {assignment.Gpio}, \"{EscapeCpp(assignment.Metric)}\", digitalRead({constant}), \"{EscapeCpp(assignment.Unit)}\");");
                }
                else
                {
                    emitCalls.AppendLine($"  // TODO reviewed driver for {EscapeCpp(assignment.ProtocolKey)} on {EscapeCpp(assignment.PinKey)}; placeholder is intentionally not transmitted.");
                }
            }

            var sketch = new StringBuilder();
            sketch.AppendLine("// Generated by LocalGPT as a reviewable planning artifact.");
            sketch.AppendLine("// Verify the exact board, electrical limits, drivers and physical wiring before compile or flash.");
            sketch.AppendLine("#include <Arduino.h>");
            if (!string.IsNullOrWhiteSpace(includes))
                sketch.AppendLine(includes);
            sketch.AppendLine();
            sketch.AppendLine($"constexpr unsigned long TELEMETRY_INTERVAL_MS = {plan.TelemetryIntervalMilliseconds}UL;");
            if (!string.IsNullOrWhiteSpace(declarations))
                sketch.AppendLine(declarations);
            if (!string.IsNullOrWhiteSpace(oneWireDeclarations))
                sketch.AppendLine(oneWireDeclarations);
            sketch.AppendLine("unsigned long lastTelemetry = 0;");
            sketch.AppendLine("unsigned long sequenceNumber = 0;");
            sketch.AppendLine();
            sketch.AppendLine("void publishReading(const char* sensorKey, const char* pinKey, int gpio, const char* metric, double value, const char* unit) {");
            sketch.AppendLine($"  Serial.print(\"{{\\\"schema\\\":\\\"localgpt.embedded.telemetry.v1\\\",\\\"deviceId\\\":\\\"{EscapeCpp(plan.DeviceName)}\\\",\\\"boardProfileKey\\\":\\\"{EscapeCpp(plan.BoardProfileKey)}\\\",\\\"transportKey\\\":\\\"{EscapeCpp(EmbeddedProtocolKeys.SerialJsonLines)}\\\",\\\"sequence\\\":\");");
            sketch.AppendLine("  Serial.print(++sequenceNumber);");
            sketch.AppendLine("  Serial.print(\",\\\"deviceTimestampMilliseconds\\\":\"); Serial.print(millis());");
            sketch.AppendLine("  Serial.print(\",\\\"readings\\\":[{\\\"sensorKey\\\":\\\"\"); Serial.print(sensorKey);");
            sketch.AppendLine("  Serial.print(\"\\\",\\\"pinKey\\\":\\\"\"); Serial.print(pinKey);");
            sketch.AppendLine("  Serial.print(\"\\\",\\\"gpio\\\":\"); Serial.print(gpio);");
            sketch.AppendLine("  Serial.print(\",\\\"metric\\\":\\\"\"); Serial.print(metric);");
            sketch.AppendLine("  Serial.print(\"\\\",\\\"value\\\":\"); Serial.print(value, 4);");
            sketch.AppendLine("  Serial.print(\",\\\"unit\\\":\\\"\"); Serial.print(unit);");
            sketch.AppendLine("  Serial.println(\"\\\",\\\"quality\\\":\\\"raw\\\"}],\\\"metadataJson\\\":\\\"{}\\\"}\");");
            sketch.AppendLine("}");
            sketch.AppendLine();
            sketch.AppendLine("void setup() {");
            sketch.AppendLine($"  Serial.begin({plan.BaudRate});");
            if (!string.IsNullOrWhiteSpace(setupPins))
                sketch.AppendLine(setupPins);
            if (!string.IsNullOrWhiteSpace(oneWireSetup))
                sketch.AppendLine(oneWireSetup);
            sketch.AppendLine("}");
            sketch.AppendLine();
            sketch.AppendLine("void loop() {");
            sketch.AppendLine("  const unsigned long now = millis();");
            sketch.AppendLine("  if (now - lastTelemetry < TELEMETRY_INTERVAL_MS) return;");
            sketch.AppendLine("  lastTelemetry = now;");
            var emitted = emitCalls.ToString().TrimEnd();
            if (!string.IsNullOrWhiteSpace(emitted))
                sketch.AppendLine(emitted);
            sketch.AppendLine("}");
            return sketch.ToString();
    
    }
    catch (Exception __serviceMethodException)
    {
        if (__serviceMethodException is OperationCanceledException)
            logger.LogDebug(__serviceMethodException, $"Service method {nameof(EmbeddedFirmwarePlanningService)}.{nameof(BuildArduinoSketch)} was canceled.");
        else
            logger.LogError(__serviceMethodException, $"Service method {nameof(EmbeddedFirmwarePlanningService)}.{nameof(BuildArduinoSketch)} failed.");
        throw;
    }
}

    /// <summary>
    /// Builds platform I/O configuration as part of the embedded firmware planning service workflow, applying the service's runtime policy, state management, and diagnostics as required.
    /// </summary>
    /// <param name="plan">Plan value supplied to the embedded firmware planning operation and used when producing its result.</param>
    /// <param name="profile">Profile value supplied to the embedded firmware planning operation and used when producing its result.</param>
    /// <returns>The string produced by the operation.</returns>
    private string BuildPlatformIoConfiguration(EmbeddedFirmwarePlan plan, EmbeddedBoardProfile? profile)
    {
    try
    {
            var board = string.IsNullOrWhiteSpace(profile?.PlatformIoBoard) ? "esp32dev" : profile.PlatformIoBoard;
            var platform = (profile?.Family ?? plan.BoardFamily).Contains("AVR", StringComparison.OrdinalIgnoreCase) || board.Equals("uno", StringComparison.OrdinalIgnoreCase)
                ? "atmelavr"
                : "espressif32";
            var libraryDependencies = plan.PinAssignments.Any(item => item.ProtocolKey == EmbeddedProtocolKeys.PhysicalOneWire)
                ? "lib_deps =\n  paulstoffregen/OneWire\n  milesburton/DallasTemperature"
                : string.Empty;
            var configuration = new StringBuilder();
            configuration.AppendLine("[platformio]");
            configuration.AppendLine("default_envs = localgpt-embedded");
            configuration.AppendLine();
            configuration.AppendLine("[env:localgpt-embedded]");
            configuration.AppendLine($"platform = {platform}");
            configuration.AppendLine($"board = {board}");
            configuration.AppendLine("framework = arduino");
            configuration.AppendLine($"monitor_speed = {plan.BaudRate}");
            if (!string.IsNullOrWhiteSpace(libraryDependencies))
                configuration.AppendLine(libraryDependencies);
            configuration.AppendLine("build_flags =");
            configuration.AppendLine($"  -DLOCALGPT_DEVICE_NAME=\\\"{EscapeIni(plan.DeviceName)}\\\"");
            configuration.AppendLine($"  -DLOCALGPT_BOARD_PROFILE=\\\"{EscapeIni(plan.BoardProfileKey)}\\\"");
            return configuration.ToString();
    
    }
    catch (Exception __serviceMethodException)
    {
        if (__serviceMethodException is OperationCanceledException)
            logger.LogDebug(__serviceMethodException, $"Service method {nameof(EmbeddedFirmwarePlanningService)}.{nameof(BuildPlatformIoConfiguration)} was canceled.");
        else
            logger.LogError(__serviceMethodException, $"Service method {nameof(EmbeddedFirmwarePlanningService)}.{nameof(BuildPlatformIoConfiguration)} failed.");
        throw;
    }
}

    /// <summary>
    /// Builds wiring markdown as part of the embedded firmware planning service workflow, applying the service's runtime policy, state management, and diagnostics as required.
    /// </summary>
    /// <param name="plan">Plan value supplied to the embedded firmware planning operation and used when producing its result.</param>
    /// <param name="profile">Profile value supplied to the embedded firmware planning operation and used when producing its result.</param>
    /// <param name="additionalRequirements">Additional requirements value supplied to the embedded firmware planning operation and used when producing its result.</param>
    /// <returns>The string produced by the operation.</returns>
    private string BuildWiringMarkdown(EmbeddedFirmwarePlan plan, EmbeddedBoardProfile? profile, string additionalRequirements)
    {
    try
    {
            var rows = plan.PinAssignments.Count == 0
                ? "| _none_ | _none_ | _Council input required_ | | | |\n"
                : string.Join(Environment.NewLine, plan.PinAssignments.Select(pin => $"| {pin.PinKey} | {pin.Gpio} | {pin.Function} | {pin.ProtocolKey} | {pin.SensorKey} | {pin.Status} |"));
            var findings = plan.Findings.Count == 0
                ? "- Approved: no deterministic conflicts were detected; exact board and electrical review is still required."
                : string.Join(Environment.NewLine, plan.Findings.Select(item => $"- **{item.Severity} / {item.Code}:** {item.Message}"));
            var steps = string.Join(Environment.NewLine, plan.WiringSteps.Select((step, index) => $"{index + 1}. {step}"));
            var contracts = string.Join(Environment.NewLine + Environment.NewLine, plan.TransportContracts.Select(contract => $"### {contract.DisplayName}\n\nProtocol: `{contract.ProtocolKey}`  \nBoundary: {contract.Boundary}\n\n```json\n{contract.ExampleEnvelopeJson}\n```"));
            var profileNotes = profile is null ? "- Board profile missing." : string.Join(Environment.NewLine, profile.Notes.Select(note => $"- {note}"));
            var requirements = string.IsNullOrWhiteSpace(additionalRequirements) ? "None supplied." : additionalRequirements.Trim();
            var markdown = new StringBuilder();
            markdown.AppendLine($"# {plan.DeviceName} wiring and LocalGPT telemetry plan");
            markdown.AppendLine();
            markdown.AppendLine($"Status: **{plan.OverallStatus}**");
            markdown.AppendLine();
            markdown.AppendLine($"Board: {plan.BoardFamily} / {plan.BoardName}  ");
            markdown.AppendLine($"Board profile: `{plan.BoardProfileKey}`  ");
            markdown.AppendLine($"Framework: {plan.Framework}  ");
            markdown.AppendLine($"Transport: `{plan.TelemetryTransport}` at {plan.BaudRate} baud");
            markdown.AppendLine();
            markdown.AppendLine("## Board-profile notes");
            markdown.AppendLine();
            markdown.AppendLine(profileNotes);
            markdown.AppendLine();
            markdown.AppendLine("## Pin assignment");
            markdown.AppendLine();
            markdown.AppendLine("| Pin | GPIO | Function | Protocol | Sensor key | Review |");
            markdown.AppendLine("|---|---:|---|---|---|---|");
            markdown.AppendLine(rows);
            markdown.AppendLine();
            markdown.AppendLine("## Deterministic review");
            markdown.AppendLine();
            markdown.AppendLine(findings);
            markdown.AppendLine();
            markdown.AppendLine("## Wiring order");
            markdown.AppendLine();
            markdown.AppendLine(steps);
            markdown.AppendLine();
            markdown.AppendLine("## Transport contracts");
            markdown.AppendLine();
            markdown.AppendLine(contracts);
            markdown.AppendLine();
            markdown.AppendLine("The embedded device packet is not itself a trusted LocalGPT command. A local gateway validates source identity, bounds, replay/timestamp policy and capability routing before creating a protected logical 1-Wire envelope. Physical 1-Wire, I²C, SPI, UART, CAN, RS-485 or custom sensor buses remain independent choices.");
            markdown.AppendLine();
            markdown.AppendLine("## Additional user requirements");
            markdown.AppendLine();
            markdown.AppendLine(requirements);
            markdown.AppendLine();
            markdown.AppendLine("## Learning round");
            markdown.AppendLine();
            markdown.AppendLine(plan.LearningRoundAdvice);
            return markdown.ToString();
    
    }
    catch (Exception __serviceMethodException)
    {
        if (__serviceMethodException is OperationCanceledException)
            logger.LogDebug(__serviceMethodException, $"Service method {nameof(EmbeddedFirmwarePlanningService)}.{nameof(BuildWiringMarkdown)} was canceled.");
        else
            logger.LogError(__serviceMethodException, $"Service method {nameof(EmbeddedFirmwarePlanningService)}.{nameof(BuildWiringMarkdown)} failed.");
        throw;
    }
}

    }
}
