using LocalGPT.BusinessObjects;

namespace LocalGPT.Services
{
    /// <summary>
    /// Coordinates minecraft project behavior for the application, centralizing the workflow, policy, and diagnostics needed by its callers.
    /// </summary>
    public sealed partial class MinecraftProjectService
    {
        /// <summary>
        /// Creates english lang as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="modId">Identifier of the mod to use for this operation.</param>
        /// <returns>The string produced by the operation.</returns>
        public string CreateEnglishLang(string modId) {
    try
    {
        return $$"""
            {
              "item.{{modId}}.city_charter": "City Charter",
              "commands.{{modId}}.report": "Living Cities Report"
            }
            """;
    }
    catch (Exception __serviceMethodException)
    {
        if (__serviceMethodException is OperationCanceledException)
            serviceLogger.LogDebug(__serviceMethodException, $"Service method {nameof(MinecraftProjectService)}.{nameof(CreateEnglishLang)} was canceled.");
        else
            serviceLogger.LogError(__serviceMethodException, $"Service method {nameof(MinecraftProjectService)}.{nameof(CreateEnglishLang)} failed.");
        throw;
    }
}
        /// <summary>
        /// Creates workspace readme as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="request">Request containing the caller-supplied values that control this operation.</param>
        /// <param name="context">Context value supplied to the council text operation and used when producing its result.</param>
        /// <param name="loader">Loader value supplied to the council text operation and used when producing its result.</param>
        /// <returns>The string produced by the operation.</returns>
        public string CreateWorkspaceReadme(MinecraftModBuildRequest request, WorkspaceContext context, string loader) {
    try
    {
        return $$"""
            # {{context.ProjectName}}

            Generated by LocalGPT as a Minecraft Java {{loader}} mod workspace.

            ## Toolchain

            - Java: JDK {{request.JavaVersion}}
            - Gradle: {{(string.IsNullOrWhiteSpace(request.GradleVersion) ? catalog.DefaultGradleVersion : request.GradleVersion)}}
            - Minecraft: {{request.MinecraftVersion}}
            - Loader: {{loader}}
            - Recommended IDE: {{request.Ide}}

            ## Build

            ```powershell
            pwsh ./build-local.ps1
            ```

            The helper script is host-neutral: it uses `JAVA_HOME` or `java` from PATH, then checks LocalGPT's per-user tool cache under the host `LocalApplicationData` folder before falling back to `gradle` from PATH.

            ## Eclipse

            Import this folder as an existing Gradle project:

            `File > Import > Gradle > Existing Gradle Project`

            After the first Gradle sync, use the Gradle tasks for `build` and, depending on loader support, `runClient`.

            ## Living Cities 0.1 starter

            This workspace intentionally starts small:

            - registers one `city_charter` item
            - adds `/livingcities report`
            - stores the full design plan in `docs/living-cities-0.1-plan.md`
            - keeps city simulation logic ready for later services/classes

            The next AI Council milestone should implement city founding with banner plus torch, scoreboard/storage state, and a minimal town hall report.
            """;
    }
    catch (Exception __serviceMethodException)
    {
        if (__serviceMethodException is OperationCanceledException)
            serviceLogger.LogDebug(__serviceMethodException, $"Service method {nameof(MinecraftProjectService)}.{nameof(CreateWorkspaceReadme)} was canceled.");
        else
            serviceLogger.LogError(__serviceMethodException, $"Service method {nameof(MinecraftProjectService)}.{nameof(CreateWorkspaceReadme)} failed.");
        throw;
    }
}

        /// <summary>
        /// Creates living cities plan as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="request">Request containing the caller-supplied values that control this operation.</param>
        /// <returns>The string produced by the operation.</returns>
        public string CreateLivingCitiesPlan(MinecraftModBuildRequest request) {
    try
    {
        return $$"""
            # Living Cities 0.1 - LocalGPT Starter Plan

            User request:

            {{request.Description}}

            ## Critical path

            1. Datapack/data structure
            2. Scoreboards or server-side saved data
            3. City founding
            4. Citizen registration
            5. Population management
            6. Minimal town hall UI/report

            ## Performance principles

            - Prefer city-level aggregate simulation over ticking every villager.
            - Avoid world-wide scans.
            - Use registered city areas, local checks, and event-driven updates.
            - Store birth year instead of recalculating and persisting age.
            - Keep town hall output useful as both player UI and debug surface.

            ## Starter implementation included

            - vanilla datapack structure using `data/<namespace>/function`
            - Minecraft `load` and `tick` function tags
            - `lc_*` scoreboard objectives
            - `living_cities:city`, `living_cities:chronicle`, and `living_cities:personalities` storage
            - trigger-based town hall/admin-book UI
            - city founding, citizen registration, population, food, security, chronicle, quest, and building functions
            - `build-local.ps1` validator that checks JSON, missing functions, placeholder files, and function references before zipping

            ## Missing LocalGPT feature report

            - Add a Minecraft Java runtime harness that copies the generated zip into a selected test world's `datapacks` folder and runs `/reload`.
            - Add optional command syntax validation against the exact installed Minecraft server version.
            - Add version-aware datapack `pack_format` lookup from the installed Minecraft version manifest.
            - Add Bedrock behavior/resource pack exporter as a separate target, not mixed into Java mod generation.
            """;
    }
    catch (Exception __serviceMethodException)
    {
        if (__serviceMethodException is OperationCanceledException)
            serviceLogger.LogDebug(__serviceMethodException, $"Service method {nameof(MinecraftProjectService)}.{nameof(CreateLivingCitiesPlan)} was canceled.");
        else
            serviceLogger.LogError(__serviceMethodException, $"Service method {nameof(MinecraftProjectService)}.{nameof(CreateLivingCitiesPlan)} failed.");
        throw;
    }
}
        /// <summary>Creates Gradle properties for a Paper server plugin workspace.</summary>
        /// <param name="request">Minecraft build request containing target versions and description.</param>
        /// <param name="context">Normalized generated-project context.</param>
        /// <param name="logger">Writes bounded generation diagnostics.</param>
        /// <returns>The generated Gradle properties text, or an empty string when generation fails.</returns>
        public string CreatePaperGradleProperties(MinecraftModBuildRequest request, WorkspaceContext context, ILogger logger)
        {
            try
            {
                serviceLogger.LogTrace("Council runtime operation {Operation} started.", nameof(CreatePaperGradleProperties));
                var versions = ResolveDependencyVersions(request, logger, "Paper");
                return $$"""
            org.gradle.jvmargs=-Xmx2G
            org.gradle.daemon=false
            org.gradle.parallel=false

            paper_api_version={{versions.PaperApiVersion}}
            plugin_id={{context.ModId}}
            plugin_name={{context.ProjectName}}
            plugin_version=0.1.0
            plugin_main={{context.PackageName}}.{{context.MainClassName}}
            plugin_authors=Generated with LocalGPT
            plugin_description={{NormalizeDescription(request.Description)}}
            maven_group={{context.PackageName}}
            """;
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Operation {Operation} failed; request and generated payloads were omitted from logs.", "CreatePaperGradleProperties");
                return string.Empty;
            }
        }

        /// <summary>Executes the create common gradle properties operation.</summary>
        /// <param name="request">Input value for request.</param>
        /// <param name="context">Input value for context.</param>
        /// <param name="logger">Input value for logger.</param>
        /// <returns>The operation result.</returns>
        public string CreateCommonGradleProperties(MinecraftModBuildRequest request, WorkspaceContext context, ILogger logger)
        {
            try
            {
                var versions = ResolveDependencyVersions(request, logger);
                var fabricApiVersion = versions.FabricApiVersion ?? ResolveMinecraftDependencyVersionInfo("Fabric", request.MinecraftVersion, logger, request.JavaVersion, request.GradleVersion)
                    .FabricApiVersion;
                var neoForgeVersion = versions.NeoForgeVersion ?? ResolveMinecraftDependencyVersionInfo("NeoForge", request.MinecraftVersion, logger, request.JavaVersion, request.GradleVersion)
                    .NeoForgeVersion;

                return $$"""
            org.gradle.jvmargs=-Xmx3G
            org.gradle.daemon=false
            org.gradle.parallel=false

            minecraft_version={{versions.RequestedMinecraftVersion}}
            minecraft_version_range=[{{versions.RequestedMinecraftVersion}},)
            loader_version={{versions.FabricLoaderVersion ?? "0.16.9"}}
            fabric_version={{fabricApiVersion}}
            neo_version={{neoForgeVersion}}
            neo_version_range=[{{neoForgeVersion}},)

            mod_id={{context.ModId}}
            mod_name={{context.ProjectName}}
            mod_license=MIT
            mod_version=0.1.0
            mod_group_id={{context.PackageName}}
            maven_group={{context.PackageName}}
            mod_authors=Generated with LocalGPT
            mod_description={{NormalizeDescription(request.Description)}}
            """;
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Operation {Operation} failed; request and generated payloads were omitted from logs.", "CreateCommonGradleProperties");
                return string.Empty;
            }
        }
        /// <summary>Executes the resolve dependency versions operation.</summary>
        /// <param name="request">Input value for request.</param>
        /// <param name="logger">Input value for logger.</param>
        /// <param name="loaderOverride">Input value for loaderOverride.</param>
        /// <returns>The operation result.</returns>
        public MinecraftDependencyVersionInfo ResolveDependencyVersions(
          MinecraftModBuildRequest request, 
          ILogger logger,
          string? loaderOverride = null) 
        {
            try
            {
                return ResolveMinecraftDependencyVersionInfo(
              loaderOverride ?? request.Loader,
              request.MinecraftVersion, 
              logger,
              request.JavaVersion,
              request.GradleVersion);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Operation {Operation} failed; request and generated payloads were omitted from logs.", "ResolveDependencyVersions");
                return CreateFallbackDependencyVersionInfo(request, loaderOverride, ex.Message);
            }
        }
          

        /// <summary>Executes the create fallback dependency version info operation.</summary>
        /// <param name="request">Input value for request.</param>
        /// <param name="loaderOverride">Input value for loaderOverride.</param>
        /// <param name="failureReason">Input value for failureReason.</param>
        /// <returns>The operation result.</returns>
        private MinecraftDependencyVersionInfo CreateFallbackDependencyVersionInfo(
            MinecraftModBuildRequest request,
            string? loaderOverride,
            string? failureReason)
        {
    try
    {
                var loader = string.IsNullOrWhiteSpace(loaderOverride) ? request.Loader : loaderOverride;
                var normalizedLoader = string.IsNullOrWhiteSpace(loader) ? "Fabric" : loader.Trim();
                var minecraftVersion = string.IsNullOrWhiteSpace(request.MinecraftVersion) ? catalog.DefaultMinecraftVersion : request.MinecraftVersion.Trim();
                var javaVersion = string.IsNullOrWhiteSpace(request.JavaVersion) ? catalog.DefaultJavaVersion : request.JavaVersion.Trim();
                var gradleVersion = string.IsNullOrWhiteSpace(request.GradleVersion) ? catalog.DefaultGradleVersion : request.GradleVersion.Trim();
                return new MinecraftDependencyVersionInfo(
                    Loader: normalizedLoader,
                    RequestedMinecraftVersion: minecraftVersion,
                    MatchedMinecraftVersion: minecraftVersion,
                    JavaVersion: javaVersion,
                    GradleVersion: gradleVersion,
                    "",
                    FabricApiVersion: null,
                    NeoForgeVersion: null,
                    PaperApiVersion: null,
                    DatapackPackFormat: normalizedLoader.Equals("Datapack", StringComparison.OrdinalIgnoreCase) ? "101.1" : null,
                    IsExactMatch: false,
                    NeedsVerification: true,
                    Notes: $"Dependency resolution failed and a conservative project-local fallback was used. {failureReason}".Trim(),
                    Source: "LocalGPT defensive fallback; verify versions with the official loader and Minecraft sources before release.");
        
    }
    catch (Exception __serviceMethodException)
    {
        if (__serviceMethodException is OperationCanceledException)
            serviceLogger.LogDebug(__serviceMethodException, $"Service method {nameof(MinecraftProjectService)}.{nameof(CreateFallbackDependencyVersionInfo)} was canceled.");
        else
            serviceLogger.LogError(__serviceMethodException, $"Service method {nameof(MinecraftProjectService)}.{nameof(CreateFallbackDependencyVersionInfo)} failed.");
        throw;
    }
}

        /// <summary>Executes the create build local script operation.</summary>
        /// <param name="request">Input value for request.</param>
        /// <param name="logger">Input value for logger.</param>
        /// <returns>The operation result.</returns>
        public string CreateBuildLocalScript(MinecraftModBuildRequest request, ILogger logger)
        {
            try
            {
                var versions = ResolveDependencyVersions(request,logger);
                var gradleVersion = versions.GradleVersion;
                return $$"""
            [CmdletBinding()]
            param(
                [string]$Task = "build"
            )

            $ErrorActionPreference = "Stop"

            function Find-ExecutableInDirectory {
                param(
                    [Parameter(Mandatory = $true)][string]$Directory,
                    [Parameter(Mandatory = $true)][string]$BaseName
                )

                if (-not (Test-Path -LiteralPath $Directory -PathType Container)) {
                    return $null
                }

                return Get-ChildItem -LiteralPath $Directory -File -ErrorAction SilentlyContinue |
                    Where-Object { $_.BaseName -eq $BaseName } |
                    Select-Object -First 1
            }

            $javaCommand = $null
            if (-not [string]::IsNullOrWhiteSpace($env:JAVA_HOME)) {
                $javaCommand = Find-ExecutableInDirectory -Directory ([IO.Path]::Combine($env:JAVA_HOME, "bin")) -BaseName "java"
            }
            if ($null -eq $javaCommand) {
                $javaCommand = Get-Command java -CommandType Application -ErrorAction SilentlyContinue
            }
            if ($null -eq $javaCommand) {
                throw "JDK {{request.JavaVersion}} was not found. Set JAVA_HOME or place java on PATH."
            }

            $javaBin = Split-Path -Parent $javaCommand.Source
            $env:JAVA_HOME = Split-Path -Parent $javaBin
            $env:Path = "$javaBin$([IO.Path]::PathSeparator)$env:Path"

            $localApplicationData = [Environment]::GetFolderPath([Environment+SpecialFolder]::LocalApplicationData)
            if (-not [string]::IsNullOrWhiteSpace($localApplicationData)) {
                $localGradleBin = [IO.Path]::Combine($localApplicationData, "LocalGPT", "Tools", "gradle-{{gradleVersion}}", "bin")
                $localGradle = Find-ExecutableInDirectory -Directory $localGradleBin -BaseName "gradle"
                if ($null -ne $localGradle) {
                    & $localGradle.FullName $Task
                    exit $LASTEXITCODE
                }
            }

            $globalGradle = Get-Command gradle -CommandType Application -ErrorAction SilentlyContinue
            if ($null -ne $globalGradle) {
                & $globalGradle.Source $Task
                exit $LASTEXITCODE
            }

            throw "Gradle {{gradleVersion}} was not found. Install Gradle or place the LocalGPT Gradle tool cache under the current user's LocalApplicationData folder."
            """;
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Operation {Operation} failed; request and generated payloads were omitted from logs.", "CreateBuildLocalScript");
                return string.Empty;
            }
        }
        /// <summary>Executes the known dependency version info versions operation.</summary>
        /// <param name="logger">Input value for logger.</param>
        /// <returns>The operation result.</returns>
        public List<CatalogEntry> KnownDependencyVersionInfoVersions (ILogger logger)
        {
            try
            {
                return new List<CatalogEntry>()
                {
                    new(
            MinecraftVersion: "26.1.2",
            FabricApiVersion: null,
            NeoForgeVersion: null,
            PaperApiVersion: null,
            JavaVersion: "25",
            Notes: "Curated LocalGPT datapack-first mapping for the Minecraft Java 26.1 stable family. Java mods/plugins need official Fabric, NeoForge, or Paper version checks before release."),
        new(
            MinecraftVersion: "26.1.1",
            FabricApiVersion: null,
            NeoForgeVersion: null,
            PaperApiVersion: null,
            JavaVersion: "25",
            Notes: "Curated LocalGPT datapack-first mapping for the Minecraft Java 26.1 stable family. Java mods/plugins need official Fabric, NeoForge, or Paper version checks before release."),
        new(
            MinecraftVersion: "26.1",
            FabricApiVersion: null,
            NeoForgeVersion: null,
            PaperApiVersion: null,
            JavaVersion: "25",
            Notes: "Curated LocalGPT datapack-first mapping for Minecraft Java 26.1. Java mods/plugins need official Fabric, NeoForge, or Paper version checks before release."),
        new(
            MinecraftVersion: "26.2-snapshot-6",
            FabricApiVersion: null,
            NeoForgeVersion: null,
            PaperApiVersion: null,
            JavaVersion: "25",
            Notes: "Curated LocalGPT snapshot datapack mapping for Minecraft Java 26.2 Snapshot 6. Use only for snapshot worlds and verify loader APIs before Java mod/plugin release."),
        new(
            MinecraftVersion: "26.2",
            FabricApiVersion: null,
            NeoForgeVersion: null,
            PaperApiVersion: null,
            JavaVersion: "25",
            Notes: "Curated LocalGPT snapshot datapack mapping for Minecraft Java 26.2. Use only for snapshot worlds and verify loader APIs before Java mod/plugin release."),
        new(
            MinecraftVersion: "1.21.4",
            FabricApiVersion: "0.116.9+1.21.4",
            NeoForgeVersion: "21.1.231",
            PaperApiVersion: "1.21.4-R0.1-SNAPSHOT",
            JavaVersion: "21",
            Notes: "Curated LocalGPT 1.21.4 mapping; NeoForge value is a cautious 1.21.x fallback and should be source-checked before release."),
        new(
            MinecraftVersion: "1.21.1",
            FabricApiVersion: "0.116.9+1.21.1",
            NeoForgeVersion: "21.1.231",
            PaperApiVersion: "1.21.1-R0.1-SNAPSHOT",
            JavaVersion: "21",
            Notes: "Curated LocalGPT 1.21.1 mapping used by Java workspace smoke tests.")
                };
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"Error in KnownDependencyVersionInfoVersions");
                return new() ;
            }
        }
        /// <summary>Executes the resolve minecraft dependency version info operation.</summary>
        /// <param name="loader">Input value for loader.</param>
        /// <param name="minecraftVersion">Input value for minecraftVersion.</param>
        /// <param name="logger">Input value for logger.</param>
        /// <param name="javaVersion">Input value for javaVersion.</param>
        /// <param name="gradleVersion">Input value for gradleVersion.</param>
        /// <returns>The operation result.</returns>
        public MinecraftDependencyVersionInfo ResolveMinecraftDependencyVersionInfo(
    string? loader,
    string? minecraftVersion,
    ILogger logger,
    string? javaVersion = null,
    string? gradleVersion = null)
        {
            try
            {
                var normalizedLoader = NormalizeLoader(loader, logger);
                var requestedMinecraftVersion = string.IsNullOrWhiteSpace(minecraftVersion)
                    ? catalog.DefaultMinecraftVersion
                    : minecraftVersion.Trim();
                var requestedGradleVersion = string.IsNullOrWhiteSpace(gradleVersion)
                    ? catalog.DefaultGradleVersion
                    : gradleVersion.Trim();
                var knownDependencyVersions = KnownDependencyVersionInfoVersions(logger);
                var entry = knownDependencyVersions.FirstOrDefault(item =>
                    requestedMinecraftVersion.Equals(item.MinecraftVersion, StringComparison.OrdinalIgnoreCase));
                var exact = entry is not null;
                entry ??= knownDependencyVersions
                    .Where(item => requestedMinecraftVersion.StartsWith(item.MinecraftVersion, StringComparison.OrdinalIgnoreCase))
                    .OrderByDescending(item => item.MinecraftVersion.Length)
                    .FirstOrDefault();
                entry ??= requestedMinecraftVersion.StartsWith("26.", StringComparison.OrdinalIgnoreCase)
                    ? knownDependencyVersions.First(item => item.MinecraftVersion == "26.1")
                    : requestedMinecraftVersion.StartsWith("1.21", StringComparison.OrdinalIgnoreCase)
                    ? knownDependencyVersions.First(item => item.MinecraftVersion == "1.21.4")
                    : knownDependencyVersions.First(item => item.MinecraftVersion == "26.1");

                var requestedJavaVersion = string.IsNullOrWhiteSpace(javaVersion)
                    ? entry.JavaVersion ?? catalog.DefaultJavaVersion
                    : javaVersion.Trim();

                var datapack = datapackService.MinecraftDatapackVersionInfoResolve(requestedMinecraftVersion, logger);
                var needsVerification = !exact ||
                    datapack.NeedsVerification ||
                    (normalizedLoader is "Fabric" or "NeoForge" or "Paper") &&
                    (entry.FabricApiVersion is null || entry.NeoForgeVersion is null || entry.PaperApiVersion is null) ||
                    normalizedLoader.Equals("NeoForge", StringComparison.OrdinalIgnoreCase) && !requestedMinecraftVersion.Equals("1.21.1", StringComparison.OrdinalIgnoreCase);

                var notes = exact
                    ? entry.Notes
                    : $"No exact curated Java-loader mapping for Minecraft {requestedMinecraftVersion}; using {entry.MinecraftVersion} as a fallback. Verify loader/API versions against official Fabric, NeoForge, and Paper sources before release.";

                return new MinecraftDependencyVersionInfo(
                    Loader: normalizedLoader,
                    RequestedMinecraftVersion: requestedMinecraftVersion,
                    MatchedMinecraftVersion: entry.MinecraftVersion,
                    JavaVersion: requestedJavaVersion,
                    GradleVersion: requestedGradleVersion,
                    "",
                    FabricApiVersion: normalizedLoader is "Fabric" ? entry.FabricApiVersion : null,
                    NeoForgeVersion: normalizedLoader is "NeoForge" ? entry.NeoForgeVersion : null,
                    PaperApiVersion: normalizedLoader is "Paper" ? entry.PaperApiVersion : null,
                    DatapackPackFormat: normalizedLoader is "Datapack" ? datapack.PackFormat : null,
                    IsExactMatch: exact && !datapack.NeedsVerification,
                    NeedsVerification: needsVerification,
                    Notes: notes,
                    Source: "LocalGPT curated Minecraft dependency catalog. Verify unknown versions with official Fabric, NeoForge, Paper, Gradle, and Minecraft version sources.");
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Could not resolve Minecraft dependency versions for loader {Loader} and version {MinecraftVersion}.", loader, minecraftVersion);
                return CreateFallbackDependencyVersionInfo(
                    new MinecraftModBuildRequest
                    {
                        Loader = loader ?? "Fabric",
                        MinecraftVersion = minecraftVersion ?? catalog.DefaultMinecraftVersion,
                        JavaVersion = javaVersion ?? catalog.DefaultJavaVersion,
                        GradleVersion = gradleVersion ?? catalog.DefaultGradleVersion
                    },
                    loader,
                    ex.Message);
            }
        }

        /// <summary>
        /// Creates minecraft system prompt as part of the council text service workflow, applying the service's runtime policy, state management, and diagnostics as required.
        /// </summary>
        /// <param name="mode">Mode value supplied to the council text operation and used when producing its result.</param>
        /// <param name="logger">Logger used to record diagnostics produced while the operation runs.</param>
        /// <returns>The string produced by the operation.</returns>
        public string CreateMinecraftSystemPrompt(string mode, ILogger logger)
        {
            try
            {
                return string.Join(Environment.NewLine, new[]
{
        $"You are a senior Minecraft Java mod engineer helping through LocalGPT in {mode}.",
        "Prefer Java Edition first. Treat Bedrock as a separate behavior/resource pack exporter.",
        "For Java code work, choose Fabric mod, NeoForge mod, or Paper plugin. For command-only vanilla systems, choose datapack.",
        "For current Minecraft Java 26.x datapacks and Java mod/plugin planning, expect Java 25 unless the target version is explicitly older.",
        "For older 1.21.x Java mods/plugins, JDK 21 remains a useful compatibility target.",
        "Produce buildable, practical implementation plans with exact files, classes, registry steps, assets, data generation, and Gradle commands.",
        "For datapacks, produce pack.mcmeta, minecraft load/tick function tags, namespace functions, validation steps, and install instructions.",
        "Help the user set up their system when tooling is missing.",
        "If LocalGPT needs a missing feature, include a 'Missing feature report' section that can be saved to memory.",
        "Label uncertain dependency versions under 'Needs verification'."
    });
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Operation {Operation} failed; request and generated payloads were omitted from logs.", "CreateMinecraftSystemPrompt");
                return string.Empty;
            }

        }
    


    }
}
