using LocalGPT.BusinessObjects;
using LocalGPT.Interfaces;

namespace LocalGPT.Services;

/// <summary>Lists user-owned Remote Control connectors without returning secret-bearing header/body/token fields.</summary>
/// <param name="connectors">Remote Control connector service.</param>
/// <param name="json">DXFunction JSON service.</param>
/// <param name="logger">Logger used for operational diagnostics.</param>
public sealed class ListRemoteControlConnectorsFunction(IRemoteControlConnectorService connectors, IDxAiFunctionJsonService json, ILogger<ListRemoteControlConnectorsFunction> logger) : IDxAiFunctionHandler
{
    /// <summary>
    /// Gets the descriptor value that forms part of the list remote control connectors function state consumed or produced by the surrounding workflow.
    /// </summary>
    /// <value>The descriptor value exposed by <see cref="ListRemoteControlConnectorsFunction"/>.</value>
    public DxaichatFunctionInfo Descriptor { get; } = new(
        "localgpt.remote_control.connector.list", "POST", "/api/dxai/functions/localgpt.remote_control.connector.list/invoke",
        "Lists the LocalGPT user's configured Remote Control REST/OData/webhook connectors and their runtime status without exposing request headers, request bodies, or webhook tokens.",
        "No parameters.", "Read-only local configuration metadata. External network access is never performed by this function.",
        IsReadOnly: true, AvailableToAi: true, SupportsDirectInvocation: true, SupportsAutomaticInvocation: true, Source: "DIHandler",
        ParameterSchemaJson: """{"type":"object","properties":{},"additionalProperties":false}""");

    /// <summary>
    /// Performs invoke for <see cref="ListRemoteControlConnectorsFunction"/>, keeping the operation consistent with the state and invariants of the surrounding list remote control connectors function workflow.
    /// </summary>
    /// <inheritdoc />
    public async Task<DxAiFunctionInvocationResult> InvokeAsync(DxAiFunctionInvocationRequest request, CancellationToken cancellationToken = default)
    {
        try
        {
            var rows = await connectors.ListAsync(cancellationToken).ConfigureAwait(false);
            var result = rows.Select(item => new
            {
                item.Key, item.DisplayName, item.Description, item.Transport, item.Method,
                UrlConfigured = !string.IsNullOrWhiteSpace(item.UrlTemplate),
                item.ResponseFormat, item.ResponseSelector, item.PollIntervalSeconds, item.TimeoutSeconds, item.MaxPayloadBytes,
                item.IsEnabled, item.NetworkEnabled, item.AllowInsecureHttp, item.AllowedHostsJson,
                WebhookTokenConfigured = item.Transport == RemoteControlTransportKind.Webhook && !string.IsNullOrWhiteSpace(item.WebhookToken),
                item.LastAttemptUtc, item.LastSuccessUtc, item.LastStatus, item.LastContentType, item.LastError
            }).ToList();
            return json.Success(result);
        }
        catch (OperationCanceledException exception) { logger.LogDebug(exception, "Listing Remote Control connectors through DXFunction was cancelled."); throw; }
        catch (Exception exception) { logger.LogError(exception, "Listing Remote Control connectors through DXFunction failed."); return new DxAiFunctionInvocationResult { Succeeded = false, Status = "Failed", Error = "Remote Control connectors could not be listed. Review LocalGPT logs." }; }
    }
}

/// <summary>Saves a user-authored Remote Control connector after explicit human confirmation.</summary>
/// <param name="connectors">Remote Control connector service.</param>
/// <param name="json">DXFunction JSON service.</param>
/// <param name="logger">Logger used for operational diagnostics.</param>
public sealed class SaveRemoteControlConnectorFunction(IRemoteControlConnectorService connectors, IDxAiFunctionJsonService json, ILogger<SaveRemoteControlConnectorFunction> logger) : IDxAiFunctionHandler
{
    /// <summary>
    /// Gets the descriptor value that forms part of the save remote control connector function state consumed or produced by the surrounding workflow.
    /// </summary>
    /// <value>The descriptor value exposed by <see cref="SaveRemoteControlConnectorFunction"/>.</value>
    public DxaichatFunctionInfo Descriptor { get; } = new(
        "localgpt.remote_control.connector.save", "POST", "/api/dxai/functions/localgpt.remote_control.connector.save/invoke",
        "Creates or updates a user-owned Remote Control REST, OData, or webhook connector. No online source is preconfigured and outbound network access must be explicitly enabled per connector.",
        "JSON body is a RemoteControlConnectorDefinition. For secrets, prefer {{var:NAME}} interpolation in header/body templates. Webhook tokens are generated by LocalGPT.",
        "Configuration mutation. Enabling outbound network access requires an explicit host allowlist. Webhook tokens are never accepted from AI parameters.",
        IsReadOnly: false, AvailableToAi: true, RequiresHumanConfirmation: true, SupportsDirectInvocation: true, SupportsAutomaticInvocation: false, Source: "DIHandler", SupportsDeferredApprovalRequest: true,
        ParameterSchemaJson: """{"type":"object","required":["key","displayName"],"properties":{"key":{"type":"string","maxLength":96},"displayName":{"type":"string","maxLength":160},"description":{"type":"string"},"transport":{"type":["integer","string"]},"method":{"type":["integer","string"]},"urlTemplate":{"type":"string"},"headersJson":{"type":"string"},"requestBodyTemplate":{"type":"string"},"requestContentType":{"type":"string"},"responseFormat":{"type":["integer","string"]},"responseSelector":{"type":"string"},"pollIntervalSeconds":{"type":"integer"},"timeoutSeconds":{"type":"integer"},"maxPayloadBytes":{"type":"integer"},"isEnabled":{"type":"boolean"},"networkEnabled":{"type":"boolean"},"allowInsecureHttp":{"type":"boolean"},"allowedHostsJson":{"type":"string"}},"additionalProperties":false}""");

    /// <summary>
    /// Performs invoke for <see cref="SaveRemoteControlConnectorFunction"/>, keeping the operation consistent with the state and invariants of the surrounding save remote control connector function workflow.
    /// </summary>
    /// <inheritdoc />
    public async Task<DxAiFunctionInvocationResult> InvokeAsync(DxAiFunctionInvocationRequest request, CancellationToken cancellationToken = default)
    {
        try
        {
            var binding = json.Bind<RemoteControlConnectorDefinition>(request.Parameters);
            if (!binding.Succeeded) return json.InvalidParameters(binding.Error);
            binding.Value.WebhookToken = string.Empty;
            var saved = await connectors.SaveAsync(binding.Value, cancellationToken).ConfigureAwait(false);
            return json.Success(new { saved.Key, saved.DisplayName, saved.Transport, saved.IsEnabled, saved.NetworkEnabled, WebhookTokenConfigured = saved.Transport == RemoteControlTransportKind.Webhook });
        }
        catch (OperationCanceledException exception) { logger.LogDebug(exception, "Saving a Remote Control connector through DXFunction was cancelled."); throw; }
        catch (Exception exception) { logger.LogError(exception, "Saving a Remote Control connector through DXFunction failed; secret-bearing fields omitted."); return new DxAiFunctionInvocationResult { Succeeded = false, Status = "Failed", Error = exception.Message }; }
    }
}

/// <summary>Deletes one user-owned Remote Control connector and dependent pipelines after human confirmation.</summary>
/// <param name="connectors">Remote Control connector service.</param>
/// <param name="json">DXFunction JSON service.</param>
/// <param name="logger">Logger used for operational diagnostics.</param>
public sealed class DeleteRemoteControlConnectorFunction(IRemoteControlConnectorService connectors, IDxAiFunctionJsonService json, ILogger<DeleteRemoteControlConnectorFunction> logger) : IDxAiFunctionHandler
{
    /// <summary>
    /// Gets the descriptor value that forms part of the delete remote control connector function state consumed or produced by the surrounding workflow.
    /// </summary>
    /// <value>The descriptor value exposed by <see cref="DeleteRemoteControlConnectorFunction"/>.</value>
    public DxaichatFunctionInfo Descriptor { get; } = new(
        "localgpt.remote_control.connector.delete", "POST", "/api/dxai/functions/localgpt.remote_control.connector.delete/invoke",
        "Deletes one Remote Control connector and pipelines that depend on it.", "JSON parameters: key required.", "Destructive local configuration mutation requiring human confirmation.",
        IsReadOnly: false, AvailableToAi: true, RequiresHumanConfirmation: true, SupportsDirectInvocation: true, SupportsAutomaticInvocation: false, Source: "DIHandler", SupportsDeferredApprovalRequest: true,
        ParameterSchemaJson: """{"type":"object","required":["key"],"properties":{"key":{"type":"string","maxLength":96}},"additionalProperties":false}""");

    /// <summary>
    /// Performs invoke for <see cref="DeleteRemoteControlConnectorFunction"/>, keeping the operation consistent with the state and invariants of the surrounding delete remote control connector function workflow.
    /// </summary>
    /// <inheritdoc />
    public async Task<DxAiFunctionInvocationResult> InvokeAsync(DxAiFunctionInvocationRequest request, CancellationToken cancellationToken = default)
    {
        try
        {
            var binding = json.Bind<RemoteControlKeyParameters>(request.Parameters);
            if (!binding.Succeeded) return json.InvalidParameters(binding.Error);
            var deleted = await connectors.DeleteAsync(binding.Value.Key, cancellationToken).ConfigureAwait(false);
            return json.Success(new { binding.Value.Key, Deleted = deleted });
        }
        catch (OperationCanceledException exception) { logger.LogDebug(exception, "Deleting a Remote Control connector through DXFunction was cancelled."); throw; }
        catch (Exception exception) { logger.LogError(exception, "Deleting a Remote Control connector through DXFunction failed."); return new DxAiFunctionInvocationResult { Succeeded = false, Status = "Failed", Error = exception.Message }; }
    }
}

/// <summary>Performs one explicitly configured REST/OData connector pull and optionally dispatches matching action pipelines.</summary>
/// <param name="connectors">Remote Control connector service.</param>
/// <param name="json">DXFunction JSON service.</param>
/// <param name="logger">Logger used for operational diagnostics.</param>
public sealed class PullRemoteControlConnectorFunction(IRemoteControlConnectorService connectors, IDxAiFunctionJsonService json, ILogger<PullRemoteControlConnectorFunction> logger) : IDxAiFunctionHandler
{
    /// <summary>
    /// Gets the descriptor value that forms part of the pull remote control connector function state consumed or produced by the surrounding workflow.
    /// </summary>
    /// <value>The descriptor value exposed by <see cref="PullRemoteControlConnectorFunction"/>.</value>
    public DxaichatFunctionInfo Descriptor { get; } = new(
        "localgpt.remote_control.connector.pull", "POST", "/api/dxai/functions/localgpt.remote_control.connector.pull/invoke",
        "Pulls one user-enabled Remote Control REST/OData connector and optionally dispatches pipelines bound to its Pull trigger.",
        "JSON parameters: key required; runPipelines optional and defaults false.",
        "Network read is restricted to the connector's explicit host allowlist. Nested action steps keep their own DXFunction approval/automatic-invocation policy.",
        IsReadOnly: true, AvailableToAi: true, SupportsDirectInvocation: true, SupportsAutomaticInvocation: true, Source: "DIHandler",
        ParameterSchemaJson: """{"type":"object","required":["key"],"properties":{"key":{"type":"string","maxLength":96},"runPipelines":{"type":"boolean"}},"additionalProperties":false}""");

    /// <summary>
    /// Performs invoke for <see cref="PullRemoteControlConnectorFunction"/>, keeping the operation consistent with the state and invariants of the surrounding pull remote control connector function workflow.
    /// </summary>
    /// <inheritdoc />
    public async Task<DxAiFunctionInvocationResult> InvokeAsync(DxAiFunctionInvocationRequest request, CancellationToken cancellationToken = default)
    {
        try
        {
            var binding = json.Bind<RemoteControlPullParameters>(request.Parameters);
            if (!binding.Succeeded) return json.InvalidParameters(binding.Error);
            var payload = await connectors.PullAsync(binding.Value.Key, binding.Value.RunPipelines, request.AutomaticInvocation, cancellationToken).ConfigureAwait(false);
            return json.Success(new { payload.ConnectorKey, payload.Trigger, payload.ContentType, payload.PayloadBytes, payload.HttpStatusCode, payload.RawText, payload.Json });
        }
        catch (OperationCanceledException exception) { logger.LogDebug(exception, "Pulling a Remote Control connector through DXFunction was cancelled."); throw; }
        catch (Exception exception) { logger.LogError(exception, "Pulling a Remote Control connector through DXFunction failed; endpoint and payload omitted."); return new DxAiFunctionInvocationResult { Succeeded = false, Status = "Failed", Error = exception.Message }; }
    }
}

/// <summary>Rotates one webhook connector token after confirmation without returning the new secret to an AI caller.</summary>
/// <param name="connectors">Remote Control connector service.</param>
/// <param name="json">DXFunction JSON service.</param>
/// <param name="logger">Logger used for operational diagnostics.</param>
public sealed class RotateRemoteControlWebhookTokenFunction(IRemoteControlConnectorService connectors, IDxAiFunctionJsonService json, ILogger<RotateRemoteControlWebhookTokenFunction> logger) : IDxAiFunctionHandler
{
    /// <summary>
    /// Gets the descriptor value that forms part of the rotate remote control webhook token function state consumed or produced by the surrounding workflow.
    /// </summary>
    /// <value>The descriptor value exposed by <see cref="RotateRemoteControlWebhookTokenFunction"/>.</value>
    public DxaichatFunctionInfo Descriptor { get; } = new(
        "localgpt.remote_control.connector.rotate_webhook_token", "POST", "/api/dxai/functions/localgpt.remote_control.connector.rotate_webhook_token/invoke",
        "Rotates a Remote Control webhook token. The new secret is intentionally not returned to the AI; retrieve/copy it from the local Remote Control UI.",
        "JSON parameters: key required.", "Secret rotation requiring human confirmation. Token values are omitted from AI results and logs.",
        IsReadOnly: false, AvailableToAi: true, RequiresHumanConfirmation: true, SupportsDirectInvocation: true, SupportsAutomaticInvocation: false, Source: "DIHandler", SupportsDeferredApprovalRequest: true,
        ParameterSchemaJson: """{"type":"object","required":["key"],"properties":{"key":{"type":"string","maxLength":96}},"additionalProperties":false}""");

    /// <summary>
    /// Performs invoke for <see cref="RotateRemoteControlWebhookTokenFunction"/>, keeping the operation consistent with the state and invariants of the surrounding rotate remote control webhook token function workflow.
    /// </summary>
    /// <inheritdoc />
    public async Task<DxAiFunctionInvocationResult> InvokeAsync(DxAiFunctionInvocationRequest request, CancellationToken cancellationToken = default)
    {
        try
        {
            var binding = json.Bind<RemoteControlKeyParameters>(request.Parameters);
            if (!binding.Succeeded) return json.InvalidParameters(binding.Error);
            _ = await connectors.RotateWebhookTokenAsync(binding.Value.Key, cancellationToken).ConfigureAwait(false);
            return json.Success(new { binding.Value.Key, Rotated = true, SecretReturned = false });
        }
        catch (OperationCanceledException exception) { logger.LogDebug(exception, "Rotating a Remote Control webhook token through DXFunction was cancelled."); throw; }
        catch (Exception exception) { logger.LogError(exception, "Rotating a Remote Control webhook token through DXFunction failed; token omitted."); return new DxAiFunctionInvocationResult { Succeeded = false, Status = "Failed", Error = exception.Message }; }
    }
}

/// <summary>Contains a Remote Control connector key for DXFunction binding.</summary>
public sealed class RemoteControlKeyParameters
{
    /// <summary>
    /// Gets or sets the stable key used to identify or correlate this remote control key parameters instance with related application state.
    /// </summary>
    /// <value>The key value exposed by <see cref="RemoteControlKeyParameters"/>.</value>
    public string Key { get; set; } = string.Empty;
}

/// <summary>Contains connector pull parameters for DXFunction binding.</summary>
public sealed class RemoteControlPullParameters
{
    /// <summary>
    /// Gets or sets the stable key used to identify or correlate this remote control pull parameters instance with related application state.
    /// </summary>
    /// <value>The key value exposed by <see cref="RemoteControlPullParameters"/>.</value>
    public string Key { get; set; } = string.Empty;
    /// <summary>Gets or sets whether matching Pull pipelines should run after a successful fetch.</summary>
    /// <value>The run pipelines value exposed by <see cref="RemoteControlPullParameters"/>.</value>
    public bool RunPipelines { get; set; }
}
