using LocalGPT.BusinessObjects.EFCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LocalGPT.Migrations;

/// <summary>Seeds database-owned operational service parameters introduced by LocalGPT 5.3.5.</summary>
[DbContext(typeof(LocalGptMemoryDbContext))]
[Migration("20261008231500_AddServiceRuntimePolicyParameters")]
public partial class AddServiceRuntimePolicyParameters : Migration
{
    /// <summary>Adds missing service parameter rows without overwriting user-edited values.</summary>
    /// <param name="migrationBuilder">Migration builder used to update persisted runtime parameters.</param>
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            INSERT OR IGNORE INTO "SystemVariables" ("Name", "ValueString", "DataType", "LastUpdated")
            VALUES
            ('McpGatewayRuntimeParametersJson','{"defaultAddress":"127.0.0.1","minimumPort":1,"maximumPort":65535,"defaultPort":51142,"rootPath":"/mcp","defaultApiKeyHeader":"X-LocalGPT-MCP-Key","modernProtocolVersion":"2026-07-28","legacyProtocolVersion":"2025-11-25","minimumCacheTtlMilliseconds":0,"maximumCacheTtlMilliseconds":86400000,"publicCacheScope":"public","privateCacheScope":"private","defaultAllowedHosts":"localhost;127.0.0.1;::1;[::1]","minimumRequestBodyBytes":1024,"maximumRequestBodyBytes":67108864,"minimumListItems":1,"maximumListItems":10000,"minimumResultCharacters":1024,"maximumResultCharacters":8000000,"apiKeyBytes":32,"enableModernProtocolWhenNoneSelected":true,"requireApiKeyForRemoteClients":true,"enableDedicatedListenerWhenNoEndpointSelected":true}','LocalGPT.BusinessObjects.McpGatewayRuntimeParameters',CURRENT_TIMESTAMP),
            ('ChatUploadWorkspaceRuntimeParametersJson','{"streamBufferBytes":131072,"immediateAnalysisMaximumBytes":8388608,"defaultWorkspaceListCount":20,"defaultFileListCount":250,"minimumFileListCount":1,"maximumFileListCount":20000,"textReaderBufferCharacters":65536,"minimumReadSegmentCharacters":1,"maximumReadSegmentCharacters":1000000}','LocalGPT.BusinessObjects.ChatUploadWorkspaceRuntimeParameters',CURRENT_TIMESTAMP),
            ('LearningProjectWorkspaceSyncRuntimeParametersJson','{"workspaceScanMaximum":200,"repositoryMarkerMaximum":20000,"gitDirectoryMaximum":2000,"includeNewerWorkspacesWhenExplicitWorkspaceIsStale":true}','LocalGPT.BusinessObjects.LearningProjectWorkspaceSyncRuntimeParameters',CURRENT_TIMESTAMP),
            ('ProviderModelRuntimeParametersJson','{"defaultSessionKeepAlive":"2m","defaultSessionContextTokens":65536,"defaultSessionTimeoutMinutes":30,"availabilityPollSeconds":2,"discoveryHttpTimeoutSeconds":10,"defaultOpenAiCompatibleEndpoint":"http://127.0.0.1:1234/v1","defaultOpenAiCompatibleApiKey":"local-no-key","defaultOpenAiEndpoint":"https://api.openai.com/v1","openAiCompatibleApiPath":"/v1","openAiCompatibleModelsPath":"/v1/models"}','LocalGPT.BusinessObjects.ProviderModelRuntimeParameters',CURRENT_TIMESTAMP),
            ('ModelBenchmarkRuntimeParametersJson','{"minimumModels":1,"maximumModels":24,"minimumProfilesPerModel":1,"maximumProfilesPerModel":16,"minimumTasks":1,"maximumTasks":4,"minimumSecondsPerCall":10,"maximumSecondsPerCall":900,"minimumImprovementPercent":0.0,"maximumImprovementPercent":50.0,"minimumRecommendedContextTokens":2048,"maximumRecommendedContextTokens":262144,"minimumRecommendedOutputTokens":128,"maximumRecommendedOutputTokens":4096,"maximumRepetitionRecoveryAttempts":8,"maximumPersistedEvidenceItems":100,"maximumExpectedSections":16,"clientTimeoutPaddingSeconds":15,"maximumTaskPromptEvidenceCharacters":24000,"maximumResponseEvidenceCharacters":48000,"maximumProviderTraceEvidenceCharacters":64000,"evidenceStreamBufferBytes":65536,"responsePreviewCharacters":320,"reviewerMaximumOutputTokens":512}','LocalGPT.BusinessObjects.ModelBenchmarkRuntimeParameters',CURRENT_TIMESTAMP),
            ('CouncilExecutionRuntimeParametersJson','{"minimumModelTimeoutSeconds":30,"defaultModelTimeoutSeconds":900,"maximumModelTimeoutSeconds":1800,"maximumRoleComplianceRetries":3,"maximumMemberRecoveryAttempts":8,"minimumFinalRecoveryOutputTokens":128,"maximumFinalRecoveryOutputTokens":32768,"maximumChildCouncilDepth":10,"maximumLoopIterations":100,"maximumContinuationRounds":6,"maximumCritiqueRounds":3,"minimumReadinessOutputTokens":32,"maximumReadinessOutputTokens":2048,"availabilityWaitDivisor":6,"minimumAvailabilityWaitSeconds":30,"maximumAvailabilityWaitSeconds":120,"recoveryOutputTokenCeiling":8192,"recoveryContextTokenCeiling":65536}','LocalGPT.BusinessObjects.CouncilExecutionRuntimeParameters',CURRENT_TIMESTAMP),
            ('CouncilGameRuntimeParametersJson','{"minimumCreatureDirectors":1,"maximumCreatureDirectors":8,"defaultCreatureDirectors":2,"minimumFrameWidth":20,"maximumFrameWidth":240,"defaultFrameWidth":80,"minimumFrameHeight":8,"maximumFrameHeight":100,"defaultFrameHeight":25,"minimumAutoplayDelayMilliseconds":250,"maximumAutoplayDelayMilliseconds":10000,"defaultAutoplayDelayMilliseconds":1000,"maximumDisplayFrames":12,"defaultForegroundColor":46,"defaultBackgroundColor":0,"minimumWorldStepScale":1,"maximumWorldStepScale":1000}','LocalGPT.BusinessObjects.CouncilGameRuntimeParameters',CURRENT_TIMESTAMP),
            ('ServiceQueryRuntimeParametersJson','{"applicationLogMaximum":200,"consoleOperatorMaximum":50,"councilSpoolerDefault":30,"councilSpoolerMaximum":100,"councilSpoolerCheckpointCount":50,"councilSpoolerMaximumSteps":512,"documentationMaximum":500,"conversationListMaximum":200,"conversationMessageMaximum":100,"humanContributionMaximum":200,"knowledgeMaximum":500,"localPathMaximumEntries":1000,"regexListMaximum":1000,"regexDxListMaximum":5000,"remoteControlExecutionMaximum":500,"toolchainCandidateMaximum":512,"toolchainRuntimeResultMaximum":5000,"webSearchMaximumResults":20}','LocalGPT.BusinessObjects.ServiceQueryRuntimeParameters',CURRENT_TIMESTAMP),
            ('LearnBaseImportRuntimeParametersJson','{"minimumManifestFiles":1,"maximumManifestFiles":20000,"minimumFileBytes":1024,"maximumManifestFileBytes":8388608,"maximumRequestedFileBytes":16777216,"minimumLearningItemsPerSource":1,"defaultLearningItemsPerSource":200,"maximumLearningItemsPerRound":10000}','LocalGPT.BusinessObjects.LearnBaseImportRuntimeParameters',CURRENT_TIMESTAMP),
            ('LocalAiRuntimeParametersJson','{"minimumImageDimension":256,"maximumImageDimension":4096,"maximumVideoWidth":1920,"maximumVideoHeight":1080,"minimumGenerationSteps":1,"maximumGenerationSteps":200,"minimumGuidanceScale":0,"maximumGuidanceScale":30,"minimumVideoFrames":8,"maximumVideoFrames":241,"minimumFramesPerSecond":1,"maximumFramesPerSecond":60,"minimumInputMegabytes":1,"maximumInputMegabytes":4096,"minimumImagePixels":1000000,"maximumImagePixels":1000000000,"minimumAudioSeconds":1,"maximumAudioSeconds":86400,"minimumAudioBytesPerSecond":1,"maximumAudioBytesPerSecond":1048576,"minimumQueueCapacity":1,"maximumQueueCapacity":1024}','LocalGPT.BusinessObjects.LocalAiRuntimeParameters',CURRENT_TIMESTAMP),
            ('ModelPresetRuntimeParametersJson','{"minimumPresetOutputTokens":512,"maximumPresetOutputTokens":262144,"minimumPresetContextTokens":2048,"maximumPresetContextTokens":262144,"minimumRouteOutputTokens":128,"minimumRouteContextTokens":512,"maximumRouteTokens":262144}','LocalGPT.BusinessObjects.ModelPresetRuntimeParameters',CURRENT_TIMESTAMP),
            ('OneWireRuntimeParametersJson','{"minimumPairingLifetimeMinutes":2,"maximumPairingLifetimeMinutes":1440,"defaultPairingLifetimeMinutes":15,"minimumTokenValidityMinutes":5,"maximumTokenValidityMinutes":525600,"minimumBroadcastIntervalSeconds":2,"maximumBroadcastIntervalSeconds":60,"minimumMessageBytes":4096,"minimumOrganicCallSeconds":1,"maximumOrganicCallSeconds":15,"defaultOrganicCallSeconds":10,"minimumOrganicResultCharacters":1000,"maximumOrganicResultCharacters":200000,"defaultOrganicResultCharacters":120000}','LocalGPT.BusinessObjects.OneWireRuntimeParameters',CURRENT_TIMESTAMP),
            ('ProjectMaintenanceRuntimeParametersJson','{"minimumBuildReviewTimeoutSeconds":10,"maximumBuildReviewTimeoutSeconds":7200,"minimumPriority":0,"maximumPriority":10000,"maximumAccessRoots":100,"maximumAccessRules":200,"maximumAccessMatches":100}','LocalGPT.BusinessObjects.ProjectMaintenanceRuntimeParameters',CURRENT_TIMESTAMP),
            ('PythonNetRuntimeParametersJson','{"defaultQueueCapacity":64,"minimumQueueCapacity":1,"maximumQueueCapacity":512}','LocalGPT.BusinessObjects.PythonNetRuntimeParameters',CURRENT_TIMESTAMP),
            ('RegexRuntimeParametersJson','{"maximumPatternCharacters":16000,"defaultTimeoutSeconds":2,"maximumTimeoutSeconds":30,"maximumStoredPatternListItems":1000}','LocalGPT.BusinessObjects.RegexRuntimeParameters',CURRENT_TIMESTAMP),
            ('RemoteKnowledgeRuntimeParametersJson','{"httpTimeoutMinutes":10,"maximumProjects":120,"downloadBufferBytes":81920}','LocalGPT.BusinessObjects.RemoteKnowledgeRuntimeParameters',CURRENT_TIMESTAMP),
            ('ToolchainRuntimeParametersJson','{"defaultCandidates":128,"minimumCandidates":1,"maximumCandidates":512,"minimumSearchDepth":0,"maximumSearchDepth":5,"maximumVisitedDirectories":3000,"maximumRuntimeResults":5000,"streamBufferBytes":131072}','LocalGPT.BusinessObjects.ToolchainRuntimeParameters',CURRENT_TIMESTAMP),
            ('HuggingFaceCatalogRuntimeParametersJson','{"minimumResults":1,"maximumResults":50,"minimumRecentWindowDays":1,"maximumRecentWindowDays":365}','LocalGPT.BusinessObjects.HuggingFaceCatalogRuntimeParameters',CURRENT_TIMESTAMP),
            ('EmbeddedFirmwareRuntimeParametersJson','{"minimumTelemetryIntervalMilliseconds":250,"maximumTelemetryIntervalMilliseconds":3600000}','LocalGPT.BusinessObjects.EmbeddedFirmwareRuntimeParameters',CURRENT_TIMESTAMP),
            ('ServiceTimingRuntimeParametersJson','{"uploadContextFreshnessMinutes":10,"aiDiscoveryTimeoutSeconds":3,"configuredChatClientTimeoutMinutes":30,"chatClientProbeTimeoutSeconds":2,"councilHeartbeatSeconds":10,"remoteControlPollingSeconds":30,"hardwareInventoryCacheMinutes":2,"councilSpoolerPersistenceDelayMilliseconds":250}','LocalGPT.BusinessObjects.ServiceTimingRuntimeParameters',CURRENT_TIMESTAMP);
            """);
    }

    /// <summary>Removes only the 5.3.5 service parameter rows when the migration is rolled back.</summary>
    /// <param name="migrationBuilder">Migration builder used to revert persisted runtime parameters.</param>
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DELETE FROM "SystemVariables"
            WHERE "Name" IN ('McpGatewayRuntimeParametersJson', 'ChatUploadWorkspaceRuntimeParametersJson', 'LearningProjectWorkspaceSyncRuntimeParametersJson', 'ProviderModelRuntimeParametersJson', 'ModelBenchmarkRuntimeParametersJson', 'CouncilExecutionRuntimeParametersJson', 'CouncilGameRuntimeParametersJson', 'ServiceQueryRuntimeParametersJson', 'LearnBaseImportRuntimeParametersJson', 'LocalAiRuntimeParametersJson', 'ModelPresetRuntimeParametersJson', 'OneWireRuntimeParametersJson', 'ProjectMaintenanceRuntimeParametersJson', 'PythonNetRuntimeParametersJson', 'RegexRuntimeParametersJson', 'RemoteKnowledgeRuntimeParametersJson', 'ToolchainRuntimeParametersJson', 'HuggingFaceCatalogRuntimeParametersJson', 'EmbeddedFirmwareRuntimeParametersJson', 'ServiceTimingRuntimeParametersJson');
            """);
    }
}
