// <auto-generated />
using System;
using LocalGPT.BusinessObjects.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalGPT.Migrations
{
    [DbContext(typeof(LocalGptMemoryDbContext))]
    partial class LocalGptMemoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("LocalGPT.BusinessObjects.ApplicationLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("LogLevelValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogLevelValue");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("LogLevelValue", "TimestampUtc");

                    b.ToTable("ApplicationLogs", (string)null);
                });


            modelBuilder.Entity("LocalGPT.BusinessObjects.CodeGenerationChangeReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ApprovalConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuildStatus")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CouncilRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionNote")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CouncilSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentProjectState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectTopicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SafetySummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspaceName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CouncilRunId");

                    b.HasIndex("ReviewHash");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("ProjectId", "Status", "UpdatedAtUtc");

                    b.ToTable("CodeGenerationChangeReviews", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.DeferredDxAiInvocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApprovalRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfirmationSummaryHash")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CouncilRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasMaxLength(64000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultSummary")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalRequestId")
                        .IsUnique();

                    b.HasIndex("CouncilRunId", "Status", "CreatedAtUtc");

                    b.ToTable("DeferredDxAiInvocations", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.HumanCollaborationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowFreeText")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CouncilRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DecisionByProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EarliestCouncilRound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrefillText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedRole")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiredBeforeCompletion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsePrompt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedResponsesText")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserResponse")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CouncilRunId", "Status");

                    b.HasIndex("Status", "UpdatedAtUtc");

                    b.HasIndex("CorrelationId", "OperationKey", "RequestedAtUtc");

                    b.ToTable("HumanCollaborationRequests", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.HumanCouncilContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CouncilRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EarliestCouncilRound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evaluation")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EvaluationVerdict")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("EvaluatedAfterRound")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EvaluatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HumanDisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("HumanRole")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InjectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CouncilRunId", "Status", "EarliestCouncilRound");

                    b.ToTable("HumanCouncilContributions", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.HumanCouncilParticipantProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingStyle")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HumanCouncilParticipantProfiles", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProject", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Requirements");

                    b.Navigation("Revisions");

                    b.Navigation("Topics");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectRevision", b =>
                {
                    b.Navigation("ChildRevisions");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectRequirement", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectTopic", b =>
                {
                    b.Navigation("KnowledgeLinks");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.ChatMemoryConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationVersion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("ProjectId", "ProjectVersionId", "UpdatedAtUtc");

                    b.ToTable("ChatMemoryConversations", (string)null);
                });


            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectRevision", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("BranchName").IsRequired().HasMaxLength(160).HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
                    b.Property<string>("CreatedBy").IsRequired().HasMaxLength(120).HasColumnType("TEXT");
                    b.Property<bool>("IsCurrent").HasColumnType("INTEGER");
                    b.Property<bool>("IsUserApproved").HasColumnType("INTEGER");
                    b.Property<Guid?>("ParentRevisionId").HasColumnType("TEXT");
                    b.Property<Guid>("ProjectId").HasColumnType("TEXT");
                    b.Property<string>("ProjectStructureJson").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("RevisionName").IsRequired().HasMaxLength(160).HasColumnType("TEXT");
                    b.Property<string>("Summary").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("ParentRevisionId");
                    b.HasIndex("ProjectId", "BranchName", "RevisionName").IsUnique();
                    b.HasIndex("ProjectId", "IsCurrent", "UpdatedAtUtc");
                    b.ToTable("LocalGptProjectRevisions", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectRequirement", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<int>("CouncilRating").HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
                    b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                    b.Property<bool>("IsUserApproved").HasColumnType("INTEGER");
                    b.Property<string>("Name").IsRequired().HasMaxLength(240).HasColumnType("TEXT");
                    b.Property<string>("Priority").IsRequired().HasMaxLength(40).HasColumnType("TEXT");
                    b.Property<Guid>("ProjectId").HasColumnType("TEXT");
                    b.Property<string>("RequiredCapability").IsRequired().HasMaxLength(240).HasColumnType("TEXT");
                    b.Property<string>("RequirementType").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<Guid?>("RevisionId").HasColumnType("TEXT");
                    b.Property<string>("SourceKind").IsRequired().HasMaxLength(160).HasColumnType("TEXT");
                    b.Property<string>("Status").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("RevisionId");
                    b.HasIndex("ProjectId", "Name").IsUnique();
                    b.HasIndex("ProjectId", "Status", "Priority");
                    b.ToTable("LocalGptProjectRequirements", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectRequirementLink", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("CouncilReviewStatus").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<bool>("IsUserApproved").HasColumnType("INTEGER");
                    b.Property<DateTime>("LinkedAtUtc").HasColumnType("TEXT");
                    b.Property<string>("LinkPurpose").IsRequired().HasMaxLength(1000).HasColumnType("TEXT");
                    b.Property<Guid>("RequirementId").HasColumnType("TEXT");
                    b.Property<string>("TargetId").IsRequired().HasMaxLength(160).HasColumnType("TEXT");
                    b.Property<string>("TargetKind").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<string>("TargetName").IsRequired().HasMaxLength(240).HasColumnType("TEXT");
                    b.Property<string>("TargetTable").IsRequired().HasMaxLength(160).HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("RequirementId", "TargetKind", "TargetName").IsUnique();
                    b.ToTable("LocalGptProjectRequirementLinks", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectArtifact", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("ArtifactKind").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<string>("CouncilReviewStatus").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
                    b.Property<string>("DataType").IsRequired().HasMaxLength(120).HasColumnType("TEXT");
                    b.Property<string>("Description").IsRequired().HasMaxLength(2000).HasColumnType("TEXT");
                    b.Property<string>("Flags").IsRequired().HasMaxLength(160).HasColumnType("TEXT");
                    b.Property<bool>("IsSensitive").HasColumnType("INTEGER");
                    b.Property<bool>("IsUserApproved").HasColumnType("INTEGER");
                    b.Property<string>("Name").IsRequired().HasMaxLength(240).HasColumnType("TEXT");
                    b.Property<Guid>("ProjectId").HasColumnType("TEXT");
                    b.Property<Guid?>("RequirementId").HasColumnType("TEXT");
                    b.Property<Guid?>("RevisionId").HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
                    b.Property<string>("Value").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("RequirementId");
                    b.HasIndex("RevisionId");
                    b.HasIndex("ProjectId", "ArtifactKind", "Name").IsUnique();
                    b.HasIndex("ProjectId", "IsUserApproved", "UpdatedAtUtc");
                    b.ToTable("LocalGptProjectArtifacts", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.ProjectDocumentImport", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("ContentHash").IsRequired().HasMaxLength(128).HasColumnType("TEXT");
                    b.Property<string>("ContentType").IsRequired().HasMaxLength(120).HasColumnType("TEXT");
                    b.Property<string>("EncodingName").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<string>("ExtractedText").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("ImportedAtUtc").HasColumnType("TEXT");
                    b.Property<bool>("IsUserApproved").HasColumnType("INTEGER");
                    b.Property<Guid>("ProjectId").HasColumnType("TEXT");
                    b.Property<Guid?>("RevisionId").HasColumnType("TEXT");
                    b.Property<string>("SafetyNotes").IsRequired().HasMaxLength(2000).HasColumnType("TEXT");
                    b.Property<string>("SourceName").IsRequired().HasMaxLength(260).HasColumnType("TEXT");
                    b.Property<string>("SourceUri").IsRequired().HasMaxLength(2048).HasColumnType("TEXT");
                    b.Property<string>("Status").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("RevisionId");
                    b.HasIndex("ProjectId", "ContentHash").IsUnique();
                    b.ToTable("ProjectDocumentImports", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.CouncilModelPreset", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
                    b.Property<bool>("CreateProjectPerRun").HasColumnType("INTEGER");
                    b.Property<string>("Description").IsRequired().HasMaxLength(1000).HasColumnType("TEXT");
                    b.Property<bool>("GenerateArtifacts").HasColumnType("INTEGER");
                    b.Property<bool>("IncludeMemory").HasColumnType("INTEGER");
                    b.Property<bool>("IsArchived").HasColumnType("INTEGER");
                    b.Property<bool>("IsDefault").HasColumnType("INTEGER");
                    b.Property<bool>("IsUserApproved").HasColumnType("INTEGER");
                    b.Property<int>("MaxContextTokens").HasColumnType("INTEGER");
                    b.Property<int>("MaxOutputTokens").HasColumnType("INTEGER");
                    b.Property<int>("MaxParallelModels").HasColumnType("INTEGER");
                    b.Property<string>("ModelNamesJson").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Name").IsRequired().HasMaxLength(160).HasColumnType("TEXT");
                    b.Property<int?>("OllamaNumGpu").HasColumnType("INTEGER");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Name").IsUnique();
                    b.HasIndex("IsArchived", "IsDefault", "UpdatedAtUtc");
                    b.ToTable("CouncilModelPresets", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.SqliteEditorFieldOverride", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("ColumnName").IsRequired().HasMaxLength(160).HasColumnType("TEXT");
                    b.Property<string>("EditorKind").IsRequired().HasMaxLength(40).HasColumnType("TEXT");
                    b.Property<string>("FormatString").IsRequired().HasMaxLength(160).HasColumnType("TEXT");
                    b.Property<string>("InputMask").IsRequired().HasMaxLength(240).HasColumnType("TEXT");
                    b.Property<bool>("IsSensitive").HasColumnType("INTEGER");
                    b.Property<string>("NullText").IsRequired().HasMaxLength(120).HasColumnType("TEXT");
                    b.Property<bool>("RequireHumanApproval").HasColumnType("INTEGER");
                    b.Property<string>("TableName").IsRequired().HasMaxLength(160).HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("TableName", "ColumnName").IsUnique();
                    b.ToTable("SqliteEditorFieldOverrides", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.CouncilKnowledgeUserRating", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("AccuracyStatus").IsRequired().HasMaxLength(80).HasColumnType("TEXT");
                    b.Property<bool>("ApprovedForCouncilUse").HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
                    b.Property<Guid>("KnowledgeEntryId").HasColumnType("TEXT");
                    b.Property<string>("Notes").IsRequired().HasMaxLength(4000).HasColumnType("TEXT");
                    b.Property<int>("Rating").HasColumnType("INTEGER");
                    b.Property<string>("RatedBy").IsRequired().HasMaxLength(120).HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("KnowledgeEntryId", "UpdatedAtUtc");
                    b.ToTable("CouncilKnowledgeUserRatings", (string)null);
                });


            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectRevision", b =>
                {
                    b.HasOne("LocalGPT.BusinessObjects.LocalGptProjectRevision", "ParentRevision").WithMany("ChildRevisions").HasForeignKey("ParentRevisionId").OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("LocalGPT.BusinessObjects.LocalGptProject", "Project").WithMany("Revisions").HasForeignKey("ProjectId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("ParentRevision");
                    b.Navigation("Project");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectRequirement", b =>
                {
                    b.HasOne("LocalGPT.BusinessObjects.LocalGptProject", "Project").WithMany("Requirements").HasForeignKey("ProjectId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("LocalGPT.BusinessObjects.LocalGptProjectRevision", "Revision").WithMany().HasForeignKey("RevisionId").OnDelete(DeleteBehavior.Restrict);
                    b.Navigation("Project");
                    b.Navigation("Revision");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectRequirementLink", b =>
                {
                    b.HasOne("LocalGPT.BusinessObjects.LocalGptProjectRequirement", "Requirement").WithMany("Links").HasForeignKey("RequirementId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectArtifact", b =>
                {
                    b.HasOne("LocalGPT.BusinessObjects.LocalGptProject", "Project").WithMany("Artifacts").HasForeignKey("ProjectId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("LocalGPT.BusinessObjects.LocalGptProjectRequirement", "Requirement").WithMany().HasForeignKey("RequirementId").OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("LocalGPT.BusinessObjects.LocalGptProjectRevision", "Revision").WithMany().HasForeignKey("RevisionId").OnDelete(DeleteBehavior.Restrict);
                    b.Navigation("Project");
                    b.Navigation("Requirement");
                    b.Navigation("Revision");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.ProjectDocumentImport", b =>
                {
                    b.HasOne("LocalGPT.BusinessObjects.LocalGptProject", "Project").WithMany().HasForeignKey("ProjectId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("LocalGPT.BusinessObjects.LocalGptProjectRevision", "Revision").WithMany().HasForeignKey("RevisionId").OnDelete(DeleteBehavior.Restrict);
                    b.Navigation("Project");
                    b.Navigation("Revision");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.CouncilKnowledgeUserRating", b =>
                {
                    b.HasOne("LocalGPT.BusinessObjects.CouncilKnowledgeEntry", "KnowledgeEntry").WithMany().HasForeignKey("KnowledgeEntryId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("KnowledgeEntry");
                });


            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectTopic", b =>
                {
                    b.HasOne("LocalGPT.BusinessObjects.LocalGptProject", "Project")
                        .WithMany("Topics")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectTopicKnowledgeLink", b =>
                {
                    b.HasOne("LocalGPT.BusinessObjects.CouncilKnowledgeEntry", "KnowledgeEntry")
                        .WithMany()
                        .HasForeignKey("KnowledgeEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalGPT.BusinessObjects.LocalGptProjectTopic", "ProjectTopic")
                        .WithMany("KnowledgeLinks")
                        .HasForeignKey("ProjectTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KnowledgeEntry");

                    b.Navigation("ProjectTopic");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectVersion", b =>
                {
                    b.HasOne("LocalGPT.BusinessObjects.LocalGptProject", "Project")
                        .WithMany("Versions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.ChatMemoryMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedbackComment")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FeedbackUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsPositiveFeedback")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Thinking")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IsPositiveFeedback", "FeedbackUpdatedAtUtc");

                    b.HasIndex("ConversationId", "SortOrder")
                        .IsUnique();

                    b.ToTable("ChatMemoryMessages", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.CouncilKnowledgeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HelpfulSources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUserApproved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastVerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SourceDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StalenessDetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StalenessDetectedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("StalenessReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersededByKnowledgeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("LastUsedAtUtc");

                    b.HasIndex("LastVerifiedAtUtc");

                    b.HasIndex("ReviewStatus");

                    b.HasIndex("Scope");

                    b.HasIndex("SupersededByKnowledgeId");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("VerificationStatus");

                    b.HasIndex("IsPinned", "UpdatedAtUtc");

                    b.HasIndex("IsUserApproved", "UpdatedAtUtc");

                    b.ToTable("CouncilKnowledgeEntries", (string)null);
                });


            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RecommendGit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("IsArchived", "UpdatedAtUtc");

                    b.ToTable("LocalGptProjects", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUserApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("LocalGptProjectTopics", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectTopicKnowledgeLink", b =>
                {
                    b.Property<Guid>("ProjectTopicId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KnowledgeEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LinkedByHuman")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LinkedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectTopicId", "KnowledgeEntryId");

                    b.HasIndex("KnowledgeEntryId");

                    b.HasIndex("LinkedAtUtc");

                    b.ToTable("LocalGptProjectTopicKnowledgeLinks", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUserConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathSnapshot")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "IsCurrent");

                    b.HasIndex("ProjectId", "Version")
                        .IsUnique();

                    b.ToTable("LocalGptProjectVersions", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.NativeCommandLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandProfile")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationMilliseconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Executable")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyDecision")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StderrPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("StdoutPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingDirectory")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Executable");

                    b.HasIndex("PolicyDecision");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("NativeCommandLogs", (string)null);
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.PromptConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Language")
                        .IsUnique();

                    b.ToTable("Prompts");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.RegexPattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Flags")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RegexPatterns");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.SystemVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SystemVariables");
                });


            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectTopic", b =>
                {
                    b.HasOne("LocalGPT.BusinessObjects.LocalGptProject", "Project")
                        .WithMany("Topics")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectTopicKnowledgeLink", b =>
                {
                    b.HasOne("LocalGPT.BusinessObjects.CouncilKnowledgeEntry", "KnowledgeEntry")
                        .WithMany()
                        .HasForeignKey("KnowledgeEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocalGPT.BusinessObjects.LocalGptProjectTopic", "ProjectTopic")
                        .WithMany("KnowledgeLinks")
                        .HasForeignKey("ProjectTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KnowledgeEntry");

                    b.Navigation("ProjectTopic");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectVersion", b =>
                {
                    b.HasOne("LocalGPT.BusinessObjects.LocalGptProject", "Project")
                        .WithMany("Versions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.ChatMemoryMessage", b =>
                {
                    b.HasOne("LocalGPT.BusinessObjects.ChatMemoryConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");
                });


            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProject", b =>
                {
                    b.Navigation("Topics");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.LocalGptProjectTopic", b =>
                {
                    b.Navigation("KnowledgeLinks");
                });

            modelBuilder.Entity("LocalGPT.BusinessObjects.ChatMemoryConversation", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
