<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <WebView2UseWinRT>False</WebView2UseWinRT>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <RootNamespace>LocalGPTWebviewWrapper</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <UseWinUI>true</UseWinUI>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	  <TargetPlatformMinVersion>10.0.26100.0</TargetPlatformMinVersion>
	  <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
	  <WindowsPackageType>None</WindowsPackageType>
	  <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
	  <RuntimeIdentifiers>win-x64;win-x86;win-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.7" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.2.0" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2270" />
    <!--<PackageReference Include="SourceGear.sqlite3" Version="3.50.4.5" />-->
    <Manifest Include="$(ApplicationManifest)" />

	
  <ProjectReference Include="..\LocalGPT\LocalGPT.csproj">
      <ReferenceOutputAssembly>True</ReferenceOutputAssembly>
      <CopyLocalSatelliteAssemblies>True</CopyLocalSatelliteAssemblies>
      <Private>True</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
