<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Version>3.1.0</Version>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
	<AssemblyName>LocalGPTInstallerConsole</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Force-Delete-Repull-LB-Slim-Model.cmd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Install-Force-Delete-Start.cmd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="LocalGPT-Install-Start.cmd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Pull-Models-RTX306012GSet.cmd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Pull-Models-RX7900XTXSet.cmd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Pull-Models-Slim.cmd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Start.cmd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Uninstall-LocalGPT-DryRun.cmd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Uninstall-LocalGPT-Force-Delete.cmd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Update-Default-Learnbase.cmd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
