-- LocalGPT AI Council knowledge seed.
-- This file is intentionally git-tracked so source-backed council knowledge can be restored into SQLite.
-- The application imports it with INSERT OR IGNORE, so user edits to existing rows are not overwritten.

INSERT OR IGNORE INTO "CouncilKnowledgeEntries"
("Id", "CreatedAtUtc", "UpdatedAtUtc", "Topic", "Scope", "Content", "Source", "HelpfulSources", "Tags", "Confidence", "IsUserApproved", "IsPinned", "IsArchived")
VALUES
(
  '54bc5a58-3a5a-4d6d-9545-13c9813f2ad8',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  'DevExpress source map for LocalGPT and TacosPortalOpen generation',
  'DevExpress Blazor',
  'For LocalGPT/TacosPortalOpen-style generation, prefer DevExpress Blazor UI controls in real Razor components and keep document/report/Office generation in ASP.NET Core backend services with safe download routes. Use DevExpress official docs for current API shape and DevExpress-Examples repositories for patterns. Important example families include Blazor AI chat function calling, multi-model chat with history, Grid plus EF Core binding/editing, FormLayout detail/edit forms, native Blazor reporting, JavaScript-based Blazor reporting, ASP.NET Core reporting best practices, Office File API Web API backends, Word/Spreadsheet Document API in Blazor Server, and Skia-based reporting for ASP.NET Core.',
  'LocalGPT SQL seed',
  'DevExpress Examples org: https://github.com/DevExpress-Examples; Blazor components docs: https://docs.devexpress.com/Blazor/400725/blazor-components; Reporting docs: https://docs.devexpress.com/XtraReports/2162/reporting',
  'seed; devexpress; blazor; aspnetcore; reporting; tacosportalopen; localgpt',
  94,
  1,
  1,
  0
),
(
  'd0dcfda6-9081-437b-91be-7d9b9628065a',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  'DevExpress DxAIChat generation rules',
  'DevExpress Blazor',
  'DxAIChat is the correct LocalGPT chat surface for model selection, visible streaming, file attachment UX, prompt suggestions, save/load, tool calling, and custom AI providers. For local Ollama/LM Studio, LocalGPT should supply the Microsoft.Extensions.AI IChatClient bridge and keep model/provider settings outside the component. Use UseStreaming for responsive output. For rich Markdown responses, set the response format/template and sanitize generated HTML before rendering. Tool calling should be exposed as explicit LocalGPT DXAiFunctions and diagnostic routes rather than arbitrary self-expansion.',
  'LocalGPT SQL seed',
  'DxAIChat docs: https://docs.devexpress.com/Blazor/DevExpress.AIIntegration.Blazor.Chat.DxAIChat; Function calling example: https://github.com/DevExpress-Examples/blazor-ai-chat-function-calling; Multi-LLM chat example: https://github.com/DevExpress-Examples/blazor-ai-chat-with-multiple-llm-services; Chat history example: https://github.com/DevExpress-Examples/blazor-multi-model-ai-chat-with-history',
  'seed; devexpress; dxaichat; ai-chat; ollama; tools; streaming',
  95,
  1,
  1,
  0
),
(
  'dff6dd3c-1f81-46f1-a4a2-1a7981d790c5',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  'DevExpress Grid/FormLayout/EF Core patterns',
  'DevExpress Blazor',
  'For LocalGPT database admin and generated business pages, use DxGrid for tabular data, DxGridDataColumn for columns, command/toolbar actions for CRUD, DxFormLayout for edit/detail forms, and explicit validation/user feedback. Persist grid layout or user presets in EF/SQLite when they affect future work. Prefer service methods over direct data access in Razor when logic grows. DevExpress examples show EF Core custom data sources, batch editing, Web API data binding, toolbar CRUD buttons, popup/separate edit forms, save/restore layout, context menus, and FormLayout detail views.',
  'LocalGPT SQL seed',
  'Grid docs: https://docs.devexpress.com/Blazor/403143/components/grid; Grid examples: https://docs.devexpress.com/Blazor/404035/components/grid/examples; Example repos: https://github.com/DevExpress-Examples/blazor-grid-custom-datasource-with-ef-core; https://github.com/DevExpress-Examples/blazor-grid-batch-editing; https://github.com/DevExpress-Examples/blazor-grid-and-toolbar; https://github.com/DevExpress-Examples/blazor-grid-save-restore-layout; https://github.com/DevExpress-Examples/blazor-grid-display-detail-information-using-form-layout',
  'seed; devexpress; dxgrid; formlayout; efcore; crud; sqlite',
  92,
  1,
  1,
  0
),
(
  '4ec5b7df-1e11-4651-bb08-51e27d9b58ee',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  'DevExpress Reporting backend and Blazor/WASM rules',
  'DevExpress Reporting',
  'DevExpress Reporting for LocalGPT should be implemented primarily in ASP.NET Core backend services/controllers. The Blazor frontend should host status, parameter UI, viewer/designer components, and safe download links. Blazor Reporting supports native Report Viewer, JavaScript-based Document Viewer, JavaScript-based Report Designer, and standalone parameter panel. Blazor WASM reporting examples require server-side reporting endpoints/controllers/providers/storage because report generation and design services are backend responsibilities. For PDF/DOCX/XLSX generation, prefer backend services and artifact/download routes instead of generating binary payloads in chat.',
  'LocalGPT SQL seed',
  'ASP.NET Core Reporting docs: https://docs.devexpress.com/AspNetCore/400597/reporting; Blazor Reports docs: https://docs.devexpress.com/Blazor/401706/components/reports; Blazor Reporting overview: https://docs.devexpress.com/XtraReports/401676/web-reporting/blazor-reporting; WASM example: https://github.com/DevExpress-Examples/reporting-blazor-wasm-get-started',
  'seed; devexpress; reporting; blazor-wasm; aspnetcore; documents; downloads',
  94,
  1,
  1,
  0
),
(
  '3a0cb09f-91b0-4851-9139-027a84a8f72b',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  'DevExpress Reporting best practices for production-like apps',
  'DevExpress Reporting',
  'When LocalGPT generates reporting features, include production concerns from DevExpress ASP.NET Core Reporting best practices: async mode where appropriate, memory and cache management, closing viewers before removing UI regions, database connection handling, CSRF protection, authentication/authorization for reports and data, custom exception handling/logging, localization, skeleton/loading UI, and server-side error diagnostics. For cross-platform ASP.NET Core reporting, prefer DevExpress.Drawing with SkiaSharp when System.Drawing is unsuitable.',
  'LocalGPT SQL seed',
  'Best practices repo: https://github.com/DevExpress-Examples/AspNetCore.Reporting.BestPractices; Support mirror: https://supportcenter.devexpress.com/ticket/details/t939061/asp-net-core-reporting-best-practices; Skia example: https://github.com/DevExpress-Examples/reporting-use-devexpress-drawing-skia-engine; Error handling: https://github.com/DevExpress-Examples/reporting-aspnet-core-handle-server-side-errors',
  'seed; devexpress; reporting; security; performance; skia; diagnostics',
  93,
  1,
  1,
  0
),
(
  '3bb74597-faf8-41b4-a497-2a13c31a8d64',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  'DevExpress Office and document generation for LocalGPT',
  'DevExpress Office',
  'For AI-requested Office/PDF examples, LocalGPT should generate backend-owned services and download artifacts. DevExpress examples show Office File API in ASP.NET Core Web API apps, converting Word/Excel to HTML, Word Document API mail-merge style letters in Blazor Server, and Spreadsheet Document API generated workbooks. The frontend should request generation, show progress/errors, and expose returned artifact links. Do not embed large binary content in DXAiChat messages.',
  'LocalGPT SQL seed',
  'Office Web API example: https://github.com/DevExpress-Examples/office-file-api-in-web-api-app; Dockerized Office API example: https://github.com/DevExpress-Examples/office-file-api-dockerize-application; Word API Blazor Server example: https://github.com/DevExpress-Examples/word-document-api-generate-and-send-letters-within-blazor-server-app; Spreadsheet API Blazor Server example: https://github.com/DevExpress-Examples/spreadsheet-document-api-create-loan-amortization-schedule-within-blazor-server-app',
  'seed; devexpress; office-file-api; word; spreadsheet; artifact-download',
  90,
  1,
  1,
  0
),
(
  'af432275-7197-4475-baa0-6722cc0ad3a8',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  'Microsoft Blazor .NET 8-10 architecture rules',
  'Microsoft Blazor',
  'For LocalGPT/TacosPortalOpen generation, distinguish Blazor Web App render modes from standalone Blazor WebAssembly. A Blazor Web App can use static SSR, Interactive Server, Interactive WebAssembly, or Interactive Auto when services/endpoints are configured. Standalone Blazor WebAssembly runs client-side and does not use render modes. Parameters passed from static parents to interactive children must be JSON serializable. LocalGPT desktop currently favors Interactive Server inside WebView2 for easier debugging and backend access; use WASM when offline/static-client behavior is explicitly requested.',
  'LocalGPT SQL seed',
  'Blazor fundamentals: https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/?view=aspnetcore-10.0; Render modes: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-10.0; Hosting models: https://learn.microsoft.com/en-us/aspnet/core/blazor/hosting-models; Tooling: https://learn.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-10.0',
  'seed; microsoft; blazor; dotnet10; render-modes; wasm; interactive-server',
  95,
  1,
  1,
  0
),
(
  '1d61a4c7-a1dd-4a26-904f-990465be07ac',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  'Microsoft Blazor WASM and static asset rules',
  'Microsoft Blazor',
  'Blazor WebAssembly downloads the .NET runtime, app assemblies, and static assets to the browser. Payload size matters: trimming, compression, and browser caching are core performance concerns. Hosted Blazor WebAssembly uses an ASP.NET Core backend to serve the client and expose APIs; standalone WASM can be hosted as static files. In LocalGPT, WASM plus DevExpress should be treated as a separate client/front-end target while native commands, EF writes, reporting generation, and artifact creation stay in backend services.',
  'LocalGPT SQL seed',
  'Hosting models: https://learn.microsoft.com/en-us/aspnet/core/blazor/hosting-models; Host and deploy: https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-10.0; Blazor static files: https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?view=aspnetcore-10.0; WASM security: https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/?view=aspnetcore-10.0',
  'seed; microsoft; blazor-wasm; static-assets; hosted-wasm; security',
  93,
  1,
  1,
  0
),
(
  'ef188b21-174e-4b18-a929-f2a5eba1bc0d',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  'Microsoft ASP.NET Core backend service rules',
  'ASP.NET Core',
  'For LocalGPT, backend capabilities belong in ASP.NET Core services and explicit routes/controllers/minimal APIs. Use DI to register services, use options/config only for bootstrap/logging/runtime settings, and persist user/application state in EF/SQLite when it should survive restarts. Use static asset guidance for Blazor assets and WebView2 packaging. Use Minimal APIs for focused diagnostics/artifact routes, and keep risky native operations behind deliberate backend services with validation and logging.',
  'LocalGPT SQL seed',
  'ASP.NET Core docs: https://learn.microsoft.com/en-us/aspnet/core/; Minimal API tutorial: https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-10.0; Dependency injection: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-10.0; Static files: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-10.0',
  'seed; microsoft; aspnetcore; minimal-api; dependency-injection; static-files',
  94,
  1,
  1,
  0
),
(
  '8b8e8906-b25b-4846-9681-ac6e9873a91d',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  'Microsoft EF Core and SQLite rules for Blazor apps',
  'EF Core',
  'DbContext is a short-lived unit-of-work and is not thread-safe. In normal ASP.NET Core requests, AddDbContext scoped lifetime is a good default. Blazor Server circuits do not align with a per-request scope, so prefer IDbContextFactory or short-lived contexts for UI events/background work. Always await EF async calls immediately. Track migrations in source control for schema evolution; for LocalGPT local admin tables, lightweight schema helpers plus idempotent SQL seeds are acceptable when preserving user-edited SQLite data. For performance, project only needed columns, index query predicates, avoid cartesian explosion, and use pagination/keyset pagination for large tables.',
  'LocalGPT SQL seed',
  'DbContext lifetime: https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/; EF migrations: https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/; Efficient querying: https://learn.microsoft.com/en-us/ef/core/performance/efficient-querying; SQLite provider: https://learn.microsoft.com/en-us/ef/core/providers/sqlite/',
  'seed; microsoft; efcore; sqlite; blazor-server; dbcontext; migrations',
  95,
  1,
  1,
  0
),
(
  '3ade0cb2-1043-4314-8a28-27ecad8ff2a3',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  'Microsoft official GitHub sample map',
  'Microsoft Samples',
  'Use only official Microsoft/dotnet repositories for baseline comparisons unless the user explicitly supplies another project. dotnet/blazor-samples contains .NET 10 Blazor Web App, Blazor WebAssembly, SignalR, Web API call, auth, OIDC/BFF, Windows auth, WASM logging, React interop, web workers, and MAUI Blazor samples. dotnet/efcore is the EF Core source and Microsoft.Data.Sqlite home. dotnet/EntityFramework.Docs and dotnet/AspNetCore.Docs are documentation sources. dotnet/eShop is the current reference app for a services-based .NET Aspire architecture. dotnet/samples contains code referenced by .NET docs.',
  'LocalGPT SQL seed',
  'Blazor samples: https://github.com/dotnet/blazor-samples; ASP.NET Core source: https://github.com/dotnet/aspnetcore; ASP.NET Core docs: https://github.com/dotnet/AspNetCore.Docs; EF Core source: https://github.com/dotnet/efcore; EF docs: https://github.com/dotnet/EntityFramework.Docs; eShop: https://github.com/dotnet/eShop; .NET samples: https://github.com/dotnet/samples',
  'seed; microsoft; github; samples; blazor; efcore; aspnetcore; eshop',
  94,
  1,
  1,
  0
),
(
  '49161f80-6ca8-4c51-9ba2-7763e9363d93',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  'LocalGPT/TacosPortalOpen generation target',
  'LocalGPT generation',
  'The main generation target is LocalGPT/TacosPortalOpen-style .NET 8-10 Blazor with DevExpress, especially Blazor Web App and Blazor WebAssembly combinations. Generated UI artifacts should be real .razor files with @page when routable, correct render mode for the chosen hosting model, dependency injection, DevExpress controls, concise tooltips/help, and no string-builder fake pages. Generated backend artifacts should be services/routes/controllers with EF/SQLite persistence where durable state is needed. Generated report/document artifacts should use backend services and downloadable files. The council should compare proposals against official DevExpress examples and Microsoft dotnet samples before recommending integration.',
  'LocalGPT SQL seed',
  'Local docs: docs/BLAZOR_DEVEXPRESS_AI_GENERATION.md; docs/ARCHITECTURE_FOR_AI.md; DevExpress examples org; dotnet/blazor-samples 10.0; user-provided TacosPortalOpen sample zip',
  'seed; localgpt; tacosportalopen; blazor; devexpress; wasm; code-generation',
  96,
  1,
  1,
  0
),
(
  '8de321d9-6255-41d6-b9aa-c051d8782629',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  'LocalGPT release build and MSIX deployment lessons',
  'LocalGPT packaging',
  'The 2026-06-02 release cycle showed that the WinUI/WebView2 package must be built with Visual Studio MSBuild, not SDK-only dotnet build, because the .wapproj DesktopBridge project uses Visual Studio targets. Build scripts must check native command exit codes explicitly because PowerShell does not fail just because dotnet or MSBuild returned nonzero. Clean generated obj intermediates for the selected platform/configuration when StaticWebAssets JSON or NuGet asset caches show null-byte corruption.',
  'LocalGPT release cycle memory',
  'Scripts: LocalGPTWebviewWrapper/build/Build-LocalGptPackage.ps1; LocalGPTWebviewWrapper/build/Publish-LocalGptRelease.ps1; package project: LocalGPTWebviewWrapper/LocalGPTWebviewWrapper (Package); release tag v0.1.1-ai-council.20260602',
  'seed; localgpt; msix; desktopbridge; powershell; release; dotnet10; build',
  98,
  1,
  1,
  0
),
(
  '5f3112ad-2f5c-4af9-b079-29502d2f5ee7',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  'LocalGPT WebView2 and DevExpress static asset packaging',
  'WinUI WebView2',
  'A plain unstyled WebView2 page meant the packaged app served Razor markup but not Blazor/DevExpress static assets. The fix was to publish the LocalGPT web project and add published wwwroot/_content, wwwroot/_framework, LocalGPT.styles.css, staticwebassets manifests, and LocalGPT.deps.json into the MSIX payload with AppxPackagePayload TargetPath entries. Copying files only into a loose AppX layout was not enough; package.map.txt had to contain the payload entries.',
  'LocalGPT release cycle memory',
  'Package payload fix in LocalGPTWebviewWrapper (Package).wapproj; diagnostics in LocalGPTWebviewWrapper/MainWindow.xaml.cs; snapshots under %LOCALAPPDATA%/LocalGPT/WebView2Diagnostics',
  'seed; localgpt; webview2; devexpress; static-web-assets; blazor; msix; diagnostics',
  98,
  1,
  1,
  0
),
(
  'e5b7f32a-2328-45ad-aea4-9a703f01d4f9',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  'LocalGPT AI Council generation and release-test workflow',
  'AI Council',
  'For release-grade AI Council feature work, prefer deterministic LocalGPT diagnostic routes first, then a final WebView2 frontend smoke. The Living Cities datapack benchmark route validated Minecraft generation without loading Ollama. The council artifact smoke routes generated real Razor, C#, DLL, and solution zip downloads. Live DXAiChat model smoke tests are valuable, but a single slow reasoning model that times out is a model-output health signal, not proof that deterministic artifact generation failed.',
  'LocalGPT release cycle memory',
  'Routes: /__diag/minecraft/datapack-benchmark, /__diag/council/artifact-smoke?target=solution, /__diag/council/artifact-smoke?target=ollama, /__artifacts/council/{fileName}; WebView2 smoke flags in %LOCALAPPDATA%/LocalGPT/runtime',
  'seed; ai-council; diagnostics; minecraft; datapack; blazor-generation; artifacts; dxaichat',
  96,
  1,
  1,
  0
),
(
  'b9b11e54-90be-46c4-9b5f-6e3952896608',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),
  'Working with Michi0403 productively',
  'Collaboration',
  'Michi0403 works best with an engineering partner that acts, verifies, and reports concrete evidence. Do not stop at proposals when he asks to fix, build, or release. Make small meaningful commits and push regularly. Be honest about failures but do not overdramatize hardware or Windows instability; distinguish GPU driver resets, display sleep, package errors, deployment errors, and model latency with logs. Use compiler/build output as the deciding authority. ' ||
  'When paths are unclear, offer a small poll with concrete options and treat the user choice as binding. Generated code and self-expansion stay sandboxed until Michi approves integration. His stubbornness is usually a product-quality signal; turn it into tests, diagnostics, and council knowledge instead of arguing.',
  'LocalGPT workflow memory',
  'docs/LOCALGPT_WORKFLOW_MEMORY.md; diagnostics and release cycle around v0.1.1-ai-council.20260602; user collaboration notes from the LocalGPT repair thread',
  'seed; collaboration; michi0403; workflow; autonomy; diagnostics; commits',
  99,
  1,
  1,
  0
);
